import {buildCanonicalChart as buildLegacyChart,parseOnsetEvents,validateAgainstChart,type CanonicalChart,type Difficulty,type Note,type OnsetEvent} from './validator.ts';

const BEAT_SONGS:Record<string,{bpm:number,offset:number,duration:number,seed:number}>={
 'my-immortal':{bpm:76,offset:232,duration:270.497,seed:4},
 'crazy-train':{bpm:136,offset:325,duration:226.325,seed:1},
 'kill-you':{bpm:107.666,offset:232,duration:264.411,seed:2},
 kryptonite:{bpm:99.384,offset:627,duration:234.292,seed:0},
 'through-fire-flames':{bpm:198.8,offset:1324,duration:300.121,seed:3},
};
const AUDIO_EXPORTS:Record<string,string>={sickness:'sicknessEvents','never-left':'neverLeftEvents','fly-eagle':'flyEagleEvents'};
const hash01=(a:number,b:number,c:number)=>{let x=(Math.imul(a+1,73856093)^Math.imul(b+11,19349663)^Math.imul(c+101,83492791))>>>0;x^=x>>>13;x=Math.imul(x,1274126177)>>>0;return (x>>>0)/4294967295};
const weightedLane=(preferred:number,recent:number[],seed:number,index:number,weight:number)=>{const scores=[0,1,2].map(lane=>{let score=1+(lane===preferred?weight*1.25:0);if(recent.at(-1)===lane)score-=1.05;if(recent.slice(-3).filter(item=>item===lane).length>=2)score-=.65;if(recent.at(-2)===lane&&recent.at(-1)!==lane)score+=.28;score+=hash01(seed,index,lane)*.45;return score});return scores.indexOf(Math.max(...scores))};
const sectionProfile=(index:number,stepsPerBar:number)=>{const bar=Math.floor(index/stepsPerBar),phrase=bar%16;if(phrase<4)return{energy:.72,style:0};if(phrase<8)return{energy:.9,style:1};if(phrase<12)return{energy:.8,style:2};return{energy:1,style:3}};

export const makeBeatChart=(bpm:number,offset:number,duration:number,difficulty:Difficulty,seed:number):Note[]=>{const beat=60000/bpm,step=difficulty==='EASY'?beat:beat/2,out:Note[]=[],recent:number[]=[];let id=0,n=0;const stepsPerBar=difficulty==='EASY'?4:8;for(let time=offset;time<duration*1000-700;time+=step,n++){const section=sectionProfile(n,stepsPerBar),accent=n%stepsPerBar===0?1:n%(stepsPerBar/2)===0?.78:.5,variation=hash01(seed,n,17),weight=Math.min(1,accent*.55+section.energy*.35+variation*.25);if(difficulty==='EASY'&&weight<.56)continue;if(difficulty==='NORMAL'&&weight<.42)continue;const preferred=(seed+section.style+n+(Math.floor(n/stepsPerBar)%3))%3,lane=weightedLane(preferred,recent,seed,n,weight);recent.push(lane);if(recent.length>6)recent.shift();const hold=weight>.88&&n%stepsPerBar>=stepsPerBar-2&&hash01(seed,n,41)>.58?beat*(difficulty==='HARD'?1.25:1):undefined;out.push({id:id++,time,lane,duration:hold});const chordChance=difficulty==='EASY'?0:difficulty==='NORMAL'?Math.max(0,(weight-.78)*1.7):Math.max(0,(weight-.62)*1.8);if(hash01(seed,n,29)<chordChance){const second=weightedLane((lane+1+(section.style%2))%3,[...recent,lane],seed+7,n,weight);if(second!==lane)out.push({id:id++,time,lane:second})}if(difficulty==='HARD'){const burst=weight>.68&&hash01(seed,n,53)<.34;if(burst&&time+step/2<duration*1000-700){const burstLane=weightedLane((lane+2)%3,[...recent,lane],seed+13,n,weight);out.push({id:id++,time:time+step/2,lane:burstLane})}if(section.style===3&&n%stepsPerBar===stepsPerBar-2){const sweep=[0,1,2,1];for(let s=1;s<=2;s++){const t=time+s*step/3;if(t<duration*1000-700)out.push({id:id++,time:t,lane:sweep[(seed+n+s)%sweep.length]})}}}}return out.sort((a,b)=>a.time-b.time||a.lane-b.lane).map((note,index)=>({...note,id:index}))};

export const makeOnsetChart=(events:readonly OnsetEvent[],difficulty:Difficulty):Note[]=>{const threshold={EASY:68,NORMAL:40,HARD:16}[difficulty],gap={EASY:300,NORMAL:145,HARD:72}[difficulty],out:Note[]=[],recent:number[]=[];let id=0,last=-Infinity;for(let i=0;i<events.length;i++){const [time,sourceLane,strength]=events[i],previous=events[Math.max(0,i-1)]?.[2]??strength,nextEvent=events[i+1],nextStrength=nextEvent?.[2]??strength,nextTime=nextEvent?.[0]??time+1000;if(strength<threshold||time-last<gap)continue;const localPeak=strength>=previous&&strength>=nextStrength?1:0,density=Math.max(0,1-Math.min(1,(nextTime-time)/700)),section=Math.floor(time/16000)%4,weight=Math.min(1,strength/100*.62+localPeak*.2+density*.1+(section===3?.08:0));if(difficulty==='EASY'&&weight<.58)continue;const preferred=(sourceLane+section+(localPeak?1:0))%3,lane=weightedLane(preferred,recent,17+section,i,weight);recent.push(lane);if(recent.length>6)recent.shift();const sustain=nextTime-time,hold=weight>.86&&sustain>620?Math.min(1350,sustain*.68):undefined;out.push({id:id++,time,lane,duration:hold});const chordChance=difficulty==='NORMAL'?Math.max(0,(weight-.82)*2):difficulty==='HARD'?Math.max(0,(weight-.64)*1.75):0;if(hash01(sourceLane+31,i,section)<chordChance){const second=weightedLane((lane+1+section)%3,[...recent,lane],31,i,weight);if(second!==lane)out.push({id:id++,time,lane:second})}if(difficulty==='HARD'&&weight>.58&&sustain>150&&hash01(sourceLane+47,i,9)<.3){const fillLane=weightedLane((lane+2)%3,[...recent,lane],47,i,weight);out.push({id:id++,time:time+Math.min(110,sustain*.42),lane:fillLane})}last=time}return out.sort((a,b)=>a.time-b.time||a.lane-b.lane).map((note,index)=>({...note,id:index}))};

export const buildCanonicalChart=(songId:string,difficulty:Difficulty,onsetSource?:string):CanonicalChart=>{const beatSong=BEAT_SONGS[songId];let notes:Note[];if(beatSong)notes=makeBeatChart(beatSong.bpm,beatSong.offset,beatSong.duration,difficulty,beatSong.seed);else if(AUDIO_EXPORTS[songId]){if(!onsetSource)throw new Error('Unsupported multiplayer chart');notes=makeOnsetChart(parseOnsetEvents(onsetSource,AUDIO_EXPORTS[songId]),difficulty)}else return buildLegacyChart(songId,difficulty,onsetSource);if(!notes.length)throw new Error('Authoritative chart is empty');return{songId,difficulty,notes,endMs:notes.at(-1)!.time+2200}};
export {validateAgainstChart};
export type {CanonicalChart,Difficulty};
