import type {Plugin} from 'vite';

const replaceRequired=(source:string,label:string,before:string,after:string)=>{
 if(!source.includes(before))throw new Error(`[account-recovery] Unable to patch ${label}; source layout changed.`);
 return source.replace(before,after);
};

const patchMain=(source:string)=>replaceRequired(
 source,
 'recovery route',
 "const [screen,setScreen]=useState<Screen>(()=>location.hash.startsWith('#player/')?'publicProfile':'home'),",
 "const [screen,setScreen]=useState<Screen>(()=>location.hash.startsWith('#player/')?'publicProfile':new URLSearchParams(location.search).get('recovery')==='password'?'account':'home'),"
);

const patchAccount=(source:string)=>{
 let code=source;
 code=replaceRequired(code,'recovery icons',"import {ArrowLeft,Check,Copy,LogIn,LogOut,Search,ShieldCheck,Trophy,User,UserPlus,Users,Zap} from 'lucide-react';","import {ArrowLeft,Check,Copy,KeyRound,LogIn,LogOut,Mail,Search,ShieldCheck,Trophy,User,UserPlus,Users,Zap} from 'lucide-react';");
 code=replaceRequired(code,'controller recovery contract',"loading:boolean;userId:string|null;email:string|null;profile:CloudPlayerProfile|null;notice:string;error:string;\n signUp:(email:string,password:string,username:string)=>Promise<void>;signIn:(email:string,password:string)=>Promise<void>;signOut:()=>Promise<void>;","loading:boolean;userId:string|null;email:string|null;profile:CloudPlayerProfile|null;notice:string;error:string;passwordRecovery:boolean;\n signUp:(email:string,password:string,username:string)=>Promise<void>;signIn:(email:string,password:string)=>Promise<void>;requestPasswordReset:(email:string)=>Promise<void>;updatePassword:(password:string)=>Promise<void>;clearPasswordRecovery:()=>Promise<void>;signOut:()=>Promise<void>;");
 code=replaceRequired(code,'recovery url helper',"const publicProfileUrl=(username:string)=>`${location.origin}${import.meta.env.BASE_URL}#player/${encodeURIComponent(username)}`;","const publicProfileUrl=(username:string)=>`${location.origin}${import.meta.env.BASE_URL}#player/${encodeURIComponent(username)}`;\nconst accountRecoveryUrl=()=>{const url=new URL(`${location.origin}${import.meta.env.BASE_URL}`);url.searchParams.set('recovery','password');return url.toString()};\nconst clearRecoveryQuery=()=>{const url=new URL(location.href);url.searchParams.delete('recovery');history.replaceState(null,'',url.pathname+(url.search||'')+url.hash)};");
 code=replaceRequired(code,'recovery state',"const[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[profile,setProfile]=useState<CloudPlayerProfile|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');","const[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[profile,setProfile]=useState<CloudPlayerProfile|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[passwordRecovery,setPasswordRecovery]=useState(()=>new URLSearchParams(location.search).get('recovery')==='password');");
 code=replaceRequired(code,'password recovery event',"client.auth.onAuthStateChange((_event:string,session:any)=>{if(!mounted)return;setMultiplayerAuthToken(session?.access_token||null);setUserId(session?.user?.id||null);","client.auth.onAuthStateChange((_event:string,session:any)=>{if(!mounted)return;if(_event==='PASSWORD_RECOVERY')setPasswordRecovery(true);setMultiplayerAuthToken(session?.access_token||null);setUserId(session?.user?.id||null);");
 code=replaceRequired(code,'safe signup message',"else setNotice('Account created. Check your email to verify it, then sign in.')","else setNotice('If this email is new, a verification link is on the way. If you already have a RhythmTap ID, sign in or reset your password.')");
 code=replaceRequired(code,'helpful sign in failure',"if(authError){setError(authError.message);return}setNotice('Signed in.');","if(authError){setError(/invalid login credentials/i.test(authError.message)?'Email or password is incorrect. Try Forgot Password if you already have a RhythmTap ID.':authError.message);return}setNotice('Signed in.');");
 code=replaceRequired(code,'password recovery actions'," const signOut=useCallback(async()=>{setError('');setNotice('');const client=await getAccountClient();await client.auth.signOut();setMultiplayerAuthToken(null);setProfile(null);setUserId(null);setEmail(null);setNotice('Signed out.')},[]);"," const requestPasswordReset=useCallback(async(address:string)=>{setError('');setNotice('');const clean=address.trim();if(!clean||!clean.includes('@')){setError('Enter the email address for your RhythmTap ID.');return}const client=await getAccountClient(),{error:resetError}=await client.auth.resetPasswordForEmail(clean,{redirectTo:accountRecoveryUrl()});if(resetError){setError(resetError.message);return}setNotice('If a RhythmTap ID exists for that email, a password reset link has been sent.')},[]);\n const updatePassword=useCallback(async(password:string)=>{setError('');setNotice('');if(password.length<8){setError('Your new password must be at least 8 characters.');return}const client=await getAccountClient(),{data:sessionData}=await client.auth.getSession();if(!sessionData?.session){setError('This password reset link is invalid or has expired. Request a new one.');return}const{error:updateError}=await client.auth.updateUser({password});if(updateError){setError(updateError.message);return}setPasswordRecovery(false);clearRecoveryQuery();setNotice('Password updated. You are signed in.');await refresh()},[refresh]);\n const clearPasswordRecovery=useCallback(async()=>{setError('');setNotice('');const client=await getAccountClient();await client.auth.signOut();setMultiplayerAuthToken(null);setPasswordRecovery(false);setProfile(null);setUserId(null);setEmail(null);clearRecoveryQuery()},[]);\n const signOut=useCallback(async()=>{setError('');setNotice('');const client=await getAccountClient();await client.auth.signOut();setMultiplayerAuthToken(null);setPasswordRecovery(false);setProfile(null);setUserId(null);setEmail(null);clearRecoveryQuery();setNotice('Signed out.')},[]);");
 code=replaceRequired(code,'controller recovery return',"return{loading,userId,email,profile,notice,error,signUp,signIn,signOut,updateProfile,refresh,recordGame,searchProfiles,loadPublicProfile};","return{loading,userId,email,profile,notice,error,passwordRecovery,signUp,signIn,requestPasswordReset,updatePassword,clearPasswordRecovery,signOut,updateProfile,refresh,recordGame,searchProfiles,loadPublicProfile};");
 code=replaceRequired(code,'auth modes',"const[mode,setMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),","const[mode,setMode]=useState<'signin'|'signup'|'forgot'|'reset'>(()=>account.passwordRecovery?'reset':'signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),");
 code=replaceRequired(code,'sync recovery mode',"useEffect(()=>{if(account.profile)setEdit({username:account.profile.username,displayName:account.profile.displayName,bio:account.profile.bio,accent:account.profile.accent,isPublic:account.profile.isPublic})},[account.profile]);","useEffect(()=>{if(account.profile)setEdit({username:account.profile.username,displayName:account.profile.displayName,bio:account.profile.bio,accent:account.profile.accent,isPublic:account.profile.isPublic})},[account.profile]);\n useEffect(()=>{if(account.passwordRecovery)setMode('reset')},[account.passwordRecovery]);");
 code=replaceRequired(code,'recovery header',"<h2>{account.profile?'PLAYER PROFILE':'ACCOUNT'}</h2>","<h2>{account.passwordRecovery?'RESET PASSWORD':account.profile?'PLAYER PROFILE':'ACCOUNT'}</h2>");
 code=replaceRequired(code,'recovery signout visibility',"{account.profile&&<button className=\"secondary compact\" onClick={()=>void account.signOut()}><LogOut/> SIGN OUT</button>}","{account.profile&&!account.passwordRecovery&&<button className=\"secondary compact\" onClick={()=>void account.signOut()}><LogOut/> SIGN OUT</button>}");
 code=replaceRequired(code,'show auth during recovery',"  {!account.profile?<div className=\"auth-wrap\">","  {account.passwordRecovery||!account.profile?<div className=\"auth-wrap\">");
 code=replaceRequired(code,'auth icon',"<div className=\"auth-icon\">{mode==='signin'?<LogIn/>:<UserPlus/>}</div>","<div className=\"auth-icon\">{mode==='signin'?<LogIn/>:mode==='forgot'?<Mail/>:mode==='reset'?<KeyRound/>:<UserPlus/>}</div>");
 code=replaceRequired(code,'auth title',"<h1>{mode==='signin'?'WELCOME BACK':'CREATE YOUR RHYTHMTAP ID'}</h1>","<h1>{mode==='signin'?'WELCOME BACK':mode==='signup'?'CREATE YOUR RHYTHMTAP ID':mode==='forgot'?'RESET YOUR PASSWORD':'SET A NEW PASSWORD'}</h1>");
 code=replaceRequired(code,'auth copy',"<p>Your levels, stats and public profile follow you across devices.</p>","<p>{mode==='forgot'?'Enter your account email and we’ll send you a secure reset link.':mode==='reset'?'Choose a new password for your RhythmTap ID.':'Your levels, stats and public profile follow you across devices.'}</p>");
 code=replaceRequired(code,'recovery email visibility',"}<label>EMAIL<input type=\"email\" value={email}","}{mode!=='reset'&&<label>EMAIL<input type=\"email\" value={email}");
 code=replaceRequired(code,'recovery email close',"placeholder=\"you@example.com\"/></label><label>PASSWORD", "placeholder=\"you@example.com\"/></label>}{mode!=='forgot'&&<label>PASSWORD");
 code=replaceRequired(code,'recovery password minimum',"autoComplete={mode==='signin'?'current-password':'new-password'} minLength={6}/></label>","autoComplete={mode==='signin'?'current-password':'new-password'} minLength={mode==='reset'?8:6}/></label>}");
 code=replaceRequired(code,'recovery submit',"<button className=\"primary\" onClick={()=>void(mode==='signin'?account.signIn(email,password):account.signUp(email,password,username))}>{mode==='signin'?<><LogIn/> SIGN IN</>:<><UserPlus/> CREATE ACCOUNT</>}</button>","<button className=\"primary\" onClick={()=>void(mode==='signin'?account.signIn(email,password):mode==='signup'?account.signUp(email,password,username):mode==='forgot'?account.requestPasswordReset(email):account.updatePassword(password))}>{mode==='signin'?<><LogIn/> SIGN IN</>:mode==='signup'?<><UserPlus/> CREATE ACCOUNT</>:mode==='forgot'?<><Mail/> SEND RESET LINK</>:<><KeyRound/> SAVE NEW PASSWORD</>}</button>");
 code=replaceRequired(code,'recovery navigation',"<button className=\"auth-switch\" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Need an account? Create one':'Already have an account? Sign in'}</button>","{mode==='signin'?<><button className=\"auth-switch\" onClick={()=>setMode('forgot')}>Forgot password?</button><button className=\"auth-switch\" onClick={()=>setMode('signup')}>Need an account? Create one</button></>:mode==='signup'?<button className=\"auth-switch\" onClick={()=>setMode('signin')}>Already have an account? Sign in</button>:mode==='forgot'?<button className=\"auth-switch\" onClick={()=>setMode('signin')}>Back to sign in</button>:<button className=\"auth-switch\" onClick={()=>void account.clearPasswordRecovery()}>Cancel password reset</button>}");
 return code;
};

export function accountRecoveryTransform():Plugin{
 return {name:'rhythtap-account-recovery-transform',enforce:'pre',transform(source,id){
  const normalized=id.replaceAll('\\','/');
  if(normalized.endsWith('/src/main.tsx'))return{code:patchMain(source),map:null};
  if(normalized.endsWith('/src/player-account.tsx'))return{code:patchAccount(source),map:null};
  return null;
 }};
}
