import type {Plugin} from 'vite';

const replaceRequired=(source:string,label:string,before:string,after:string)=>{
 if(!source.includes(before))throw new Error(`[accounts] Unable to patch ${label}; transformed app layout changed.`);
 return source.replace(before,after);
};

export function accountTransform():Plugin{
 return {name:'rhythtap-account-transform',enforce:'pre',transform(source,id){
  if(!id.replaceAll('\\','/').endsWith('/src/main.tsx'))return null;
  let code=source;
  code=replaceRequired(code,'imports',"import {MultiplayerHud,MultiplayerLobby,MultiplayerResultOverlay,useMultiplayerSession,type MultiplayerLaunch,type MultiplayerSession} from './multiplayer';","import {MultiplayerHud,MultiplayerLobby,MultiplayerResultOverlay,useMultiplayerSession,type MultiplayerLaunch,type MultiplayerSession} from './multiplayer';\nimport {AccountScreen,PublicProfileScreen,usePlayerAccount,type PlayerAccountController} from './player-account';");
  code=replaceRequired(code,'screen type',"type Screen='home'|'select'|'library'|'leaderboard'|'multiplayer'|'game'|'results'|'settings'|'achievements';","type Screen='home'|'select'|'library'|'leaderboard'|'multiplayer'|'account'|'publicProfile'|'game'|'results'|'settings'|'achievements';");
  code=replaceRequired(code,'public profile route',"const [screen,setScreen]=useState<Screen>('home'),","const [screen,setScreen]=useState<Screen>(()=>location.hash.startsWith('#player/')?'publicProfile':'home'),");
  code=replaceRequired(code,'account state'," const [result,setResult]=useState<GameResult>({score:0,accuracy:0,maxCombo:0,counts:{PERFECT:0,GREAT:0,GOOD:0,MISS:0},xpEarned:0,dailyBonus:0,levelUp:false,previousLevel:1});\n const [multiplayerLaunch,setMultiplayerLaunch]=useState<MultiplayerLaunch|null>(null);"," const [result,setResult]=useState<GameResult>({score:0,accuracy:0,maxCombo:0,counts:{PERFECT:0,GREAT:0,GOOD:0,MISS:0},xpEarned:0,dailyBonus:0,levelUp:false,previousLevel:1});\n const playerAccount=usePlayerAccount();\n const [multiplayerLaunch,setMultiplayerLaunch]=useState<MultiplayerLaunch|null>(null);");
  code=replaceRequired(code,'cloud progression sync'," const multiplayerSession=useMultiplayerSession(multiplayerLaunch,(startAt,hostStartAt,matchId,submissionToken)=>{setMultiplayerLaunch(current=>current?{...current,startAt,hostStartAt,matchId,submissionToken}:current);setScreen('game')});"," const multiplayerSession=useMultiplayerSession(multiplayerLaunch,(startAt,hostStartAt,matchId,submissionToken)=>{setMultiplayerLaunch(current=>current?{...current,startAt,hostStartAt,matchId,submissionToken}:current);setScreen('game')});\n useEffect(()=>{if(!playerAccount.profile)return;setProfile({xp:playerAccount.profile.xp,level:playerAccount.profile.level});setStats(current=>({...current,songsCompleted:playerAccount.profile!.songsCompleted,perfectHits:playerAccount.profile!.perfectHits,bestCombo:playerAccount.profile!.bestCombo}))},[playerAccount.profile?.xp,playerAccount.profile?.level,playerAccount.profile?.songsCompleted,playerAccount.profile?.perfectHits,playerAccount.profile?.bestCombo]);\n useEffect(()=>{if(multiplayerSession.verifiedLocal)void playerAccount.refresh()},[multiplayerSession.verifiedLocal]);");
  code=replaceRequired(code,'cloud result recording',"setResult({...r,xpEarned,dailyBonus,levelUp:level>previousLevel,previousLevel});setScreen('results')};","setResult({...r,xpEarned,dailyBonus,levelUp:level>previousLevel,previousLevel});if(!multiplayerLaunch)void playerAccount.recordGame({songId:song.id,difficulty,score:r.score,accuracy:r.accuracy,maxCombo:r.maxCombo,perfectHits:r.counts.PERFECT});setScreen('results')};");
  code=replaceRequired(code,'home render',"{screen==='home'&&<Home profile={profile} stats={stats} onPlay={()=>setScreen('select')} onMultiplayer={()=>setScreen('multiplayer')} onLibrary={()=>setScreen('library')} onAchievements={()=>setScreen('achievements')} onSettings={()=>setScreen('settings')}/>} ".trim(),"{screen==='home'&&<Home profile={profile} stats={stats} account={playerAccount} onPlay={()=>setScreen('select')} onMultiplayer={()=>setScreen('multiplayer')} onAccount={()=>setScreen('account')} onLibrary={()=>setScreen('library')} onAchievements={()=>setScreen('achievements')} onSettings={()=>setScreen('settings')}/>} ".trim());
  code=replaceRequired(code,'account screens',"  {screen==='multiplayer'&&<MultiplayerLobby","  {screen==='account'&&<AccountScreen account={playerAccount} back={()=>setScreen('home')}/>}\n  {screen==='publicProfile'&&<PublicProfileScreen account={playerAccount} back={()=>{history.replaceState(null,'',location.pathname+location.search);setScreen('home')}}/>}\n  {screen==='multiplayer'&&<MultiplayerLobby");
  code=replaceRequired(code,'home signature',"function Home({profile,stats,onPlay,onMultiplayer,onLibrary,onAchievements,onSettings}:{profile:Profile,stats:Stats,onPlay:()=>void,onMultiplayer:()=>void,onLibrary:()=>void,onAchievements:()=>void,onSettings:()=>void})","function Home({profile:localProfile,stats:localStats,account,onPlay,onMultiplayer,onAccount,onLibrary,onAchievements,onSettings}:{profile:Profile,stats:Stats,account:PlayerAccountController,onPlay:()=>void,onMultiplayer:()=>void,onAccount:()=>void,onLibrary:()=>void,onAchievements:()=>void,onSettings:()=>void})");
  code=replaceRequired(code,'home cloud profile',"{const progress=(profile.xp-xpFloor(profile.level))/(xpCeil(profile.level)-xpFloor(profile.level))*100,dailyProgress=Math.min(2,stats.dailyPlays),completedAchievements=achievements.filter(a=>a.value(stats)>=a.target).length;","{const profile=account.profile?{xp:account.profile.xp,level:account.profile.level}:localProfile,stats=account.profile?{...localStats,songsCompleted:account.profile.songsCompleted,perfectHits:account.profile.perfectHits,bestCombo:account.profile.bestCombo}:localStats,progress=(profile.xp-xpFloor(profile.level))/(xpCeil(profile.level)-xpFloor(profile.level))*100,dailyProgress=Math.min(2,stats.dailyPlays),completedAchievements=achievements.filter(a=>a.value(stats)>=a.target).length;");
  code=replaceRequired(code,'home identity',"<strong>PLAYER</strong>","<strong>{account.profile?.displayName||account.profile?.username||'PLAYER'}</strong>");
  code=replaceRequired(code,'home account button',"<div className=\"quick-grid\"><button onClick={onMultiplayer}><span><User/></span><div><small>ONLINE BATTLE</small><strong>2-player realtime score battle</strong></div><ChevronRight/></button><button onClick={onLibrary}><span><Music2/></span><div><small>MY CHARTS</small><strong>Imported song library</strong></div><ChevronRight/></button><button onClick={onAchievements}><span><Trophy/></span><div><small>ACHIEVEMENTS</small><strong>{completedAchievements} / {achievements.length} earned</strong></div><ChevronRight/></button></div>","<div className=\"quick-grid\"><button onClick={onAccount}><span><User/></span><div><small>{account.profile?'MY PROFILE':'RHYTHMTAP ID'}</small><strong>{account.profile?`@${account.profile.username} · Level ${account.profile.level}`:'Sign in · Save progression'}</strong></div><ChevronRight/></button><button onClick={onMultiplayer}><span><User/></span><div><small>ONLINE BATTLE</small><strong>2-player realtime score battle</strong></div><ChevronRight/></button><button onClick={onLibrary}><span><Music2/></span><div><small>MY CHARTS</small><strong>Imported song library</strong></div><ChevronRight/></button><button onClick={onAchievements}><span><Trophy/></span><div><small>ACHIEVEMENTS</small><strong>{completedAchievements} / {achievements.length} earned</strong></div><ChevronRight/></button></div>");
  return {code,map:null};
 }};
}
