import type {Plugin} from 'vite';

const replaceRequired=(source:string,label:string,before:string,after:string)=>{
 if(!source.includes(before))throw new Error(`[battle-experience] Unable to patch ${label}; source layout changed.`);
 return source.replace(before,after);
};

const replaceFrom=(source:string,label:string,startMarker:string,replacement:string)=>{
 const start=source.indexOf(startMarker);
 if(start<0)throw new Error(`[battle-experience] Unable to patch ${label}; marker missing.`);
 return source.slice(0,start)+replacement;
};

const patchMain=(source:string)=>{
 let code=source;
 code=replaceRequired(code,'account gate',"onMultiplayer={()=>setScreen('multiplayer')}","onMultiplayer={()=>setScreen(playerAccount.profile?'multiplayer':'account')}");
 code=replaceRequired(code,'account multiplayer identity',"<MultiplayerLobby songs={library.filter(item=>!item.id.startsWith('tap-'))} profileLevel={profile.level} initialDifficulty={difficulty}","<MultiplayerLobby songs={library.filter(item=>!item.id.startsWith('tap-'))} profileLevel={playerAccount.profile?.level??profile.level} playerId={playerAccount.userId!} displayName={playerAccount.profile?.displayName||playerAccount.profile?.username||'PLAYER'} initialDifficulty={difficulty}");
 return code;
};

const patchAccount=(source:string)=>{
 let code=source;
 code=replaceRequired(code,'auth bridge import',"import {SUPABASE_ANON_KEY,SUPABASE_ESM,SUPABASE_URL} from './multiplayer-common';","import {SUPABASE_ANON_KEY,SUPABASE_ESM,SUPABASE_URL,setMultiplayerAuthToken} from './multiplayer-common';");
 code=replaceRequired(code,'session token bridge',"session=data?.session||null;setUserId(session?.user?.id||null);", "session=data?.session||null;setMultiplayerAuthToken(session?.access_token||null);setUserId(session?.user?.id||null);");
 code=replaceRequired(code,'auth listener token bridge',"client.auth.onAuthStateChange((_event:string,session:any)=>{if(!mounted)return;setUserId(session?.user?.id||null);", "client.auth.onAuthStateChange((_event:string,session:any)=>{if(!mounted)return;setMultiplayerAuthToken(session?.access_token||null);setUserId(session?.user?.id||null);");
 code=replaceRequired(code,'sign out token bridge',"await client.auth.signOut();setProfile(null);setUserId(null);", "await client.auth.signOut();setMultiplayerAuthToken(null);setProfile(null);setUserId(null);");
 return code;
};

const patchCommon=(source:string)=>{
 let code=source;
 code=replaceRequired(code,'auth token storage',"export const localStartFromHost=(hostStartAt:number,offsetMs:number)=>hostStartAt-offsetMs;","export const localStartFromHost=(hostStartAt:number,offsetMs:number)=>hostStartAt-offsetMs;\nlet multiplayerAuthToken='';\nexport const setMultiplayerAuthToken=(token:string|null)=>{multiplayerAuthToken=token||''};");
 code=replaceRequired(code,'authenticated battle requests',"export const functionRequest=async(body:unknown)=>{const response=await fetch(`${SUPABASE_URL}/functions/v1/validate-match`,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_ANON_KEY,'authorization':`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify(body)});", "export const functionRequest=async(body:unknown)=>{if(!multiplayerAuthToken)throw new Error('Sign in to play Online Battle');const response=await fetch(`${SUPABASE_URL}/functions/v1/validate-match`,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_ANON_KEY,'authorization':`Bearer ${multiplayerAuthToken}`},body:JSON.stringify(body)});");
 return code;
};

const lobbyRender=` const roomHeadline=status==='full'?'BATTLE IS FULL':status==='error'?'COULDN’T JOIN BATTLE':!audioReady?'GETTING THE TRACK READY…':players.length<2?'WAITING FOR A RIVAL…':!bothReady?'RIVAL IS GETTING READY…':'BOTH PLAYERS READY';
 const roomSubline=status==='full'?'Try another battle code.':status==='error'?'Check your connection and try again.':players.length<2?'Share the battle code with a friend.':bothReady?'The host can start whenever you’re ready.':'Almost there.';
 if(roomCode)return <section className="multiplayer screen battle-room"><header><button className="icon" onClick={()=>{void cleanup();setRoomCode('');setStatus('idle')}} aria-label="Leave battle"><ArrowLeft/></button><div><small>ONLINE BATTLE</small><h2>BACKSTAGE</h2></div><Zap/></header><div className="mp-room-code"><span>INVITE CODE</span><strong>{roomCode}</strong><button className="icon" onClick={copyCode} aria-label="Copy battle code"><Copy/></button></div><div className="mp-player-grid">{[0,1].map(index=>{const player=players[index];return <div key={index} className={'mp-player '+(player?'online':'waiting')+(index===0?' host':' challenger')}><div className="mp-avatar"><Users/></div><small>{index===0?'HOST':'RIVAL'}</small><strong>{player?.name??'OPEN SPOT'}</strong><span>{player?(readyMap[player.playerId]?'READY TO PLAY':'GETTING READY…'):'WAITING FOR PLAYER'}</span></div>})}</div><div className="mp-versus"><span></span><strong>VS</strong><span></span></div><div className="mp-panel"><div className="section-label"><span>SETLIST</span><small>{isHost?'YOU PICK THE TRACK':'HOST PICKS THE TRACK'}</small></div><div className="mp-song-list">{songs.map(song=>{const locked=profileLevel<song.unlockLevel;return <button key={song.id} disabled={!isHost||locked} className={songId===song.id?'active':''} onClick={()=>chooseSong(song.id)}><span><small>{song.artist}</small><strong>{song.title}</strong></span><em>{locked?'LOCKED':songId===song.id?'ON STAGE':'PICK'}</em></button>})}</div></div><div className="difficulty mp-difficulty" aria-label="Battle difficulty">{(['EASY','NORMAL','HARD'] as MultiplayerDifficulty[]).map(item=><button key={item} disabled={!isHost} className={difficulty===item?'active':''} onClick={()=>chooseDifficulty(item)}><span>{item}</span><small>{item==='EASY'?'WARM UP':item==='NORMAL'?'HEADLINER':'NO MERCY'}</small></button>)}</div><div className="mp-room-footer"><div><Music2/><span><strong>{roomHeadline}</strong><small>{roomSubline}</small></span></div>{isHost?<button className="primary" disabled={status!=='connected'||!bothReady} onClick={()=>{void startMatch()}}><Play fill="currentColor"/> START BATTLE</button>:<div className="mp-wait"><LoaderCircle/> WAITING FOR HOST</div>}</div>{(status==='error'||status==='full'||message.includes('FAILED'))&&<div className="mp-message">{roomHeadline}</div>}</section>;
 return <section className="multiplayer screen battle-entry"><header><button className="icon" onClick={onBack} aria-label="Back"><ArrowLeft/></button><div><small>RHYTHMTAP ONLINE</small><h2>BATTLE</h2></div><Trophy/></header><div className="mp-hero"><div className="mp-hero-icon"><Music2/></div><small>ONE TRACK · TWO PLAYERS</small><h1>TAKE THE STAGE.<br/><i>BEAT YOUR RIVAL.</i></h1><p>Pick a song, invite a player, and prove who owns the chart.</p></div><div className="mp-account-chip"><div className="mp-avatar"><Users/></div><span><small>PLAYING AS</small><strong>{name}</strong></span><em>RHYTHMTAP ID</em></div><div className="mp-actions"><button className="primary mp-create" onClick={()=>{const next=makeCode();setCode(next);void connect(next,true)}}><Trophy/> CREATE BATTLE</button><div className="mp-divider"><span>HAVE A CODE?</span></div><div className="mp-join"><input value={code} maxLength={6} onChange={event=>setCode(cleanCode(event.target.value))} placeholder="ABC123" inputMode="text" aria-label="Battle code"/><button className="secondary" disabled={code.length!==6||status==='connecting'} onClick={()=>{void connect(code,false)}}>{status==='connecting'?<LoaderCircle/>:<Play/>} JOIN</button></div></div>{message&&status==='error'&&<div className="mp-message">COULDN’T JOIN THAT BATTLE</div>}<div className="mp-history"><div className="mp-history-title"><span><small>YOUR ENCORE</small><strong>RECENT BATTLES</strong></span><Trophy/></div>{history.length?history.slice(0,5).map(item=><div className="mp-history-row" key={item.matchId}><strong className={'outcome '+item.outcome.toLowerCase()}>{item.outcome}</strong><span><b>{songs.find(song=>song.id===item.songId)?.title??item.songId}</b><small>{item.difficulty} · vs {item.opponentName}</small></span><em>{item.score.toLocaleString()}<small>{item.opponentScore===null?'':(' — '+item.opponentScore.toLocaleString())}</small></em></div>):<p>Your battle history will show up here after your first match.</p>}</div><div className="mp-account-note"><Users/><span><strong>BATTLES BELONG TO YOUR RHYTHMTAP ID</strong><small>Your wins, losses, and scores stay connected to your player profile.</small></span></div></section>;
}`;

const patchLobby=(source:string)=>{
 let code=source;
 code=replaceRequired(code,'music icons',"import {ArrowLeft,Copy,LoaderCircle,Play,Radio,RefreshCw,Users,Wifi,WifiOff,Zap} from 'lucide-react';","import {ArrowLeft,Copy,LoaderCircle,Music2,Play,Radio,RefreshCw,Trophy,Users,Wifi,WifiOff,Zap} from 'lucide-react';");
 code=replaceRequired(code,'account lobby signature',"export function MultiplayerLobby({songs,profileLevel,initialDifficulty,onBack,onLaunch}:{songs:MultiplayerSong[],profileLevel:number,initialDifficulty:MultiplayerDifficulty,onBack:()=>void,onLaunch:(launch:MultiplayerLaunch)=>void}){","export function MultiplayerLobby({songs,profileLevel,playerId,displayName,initialDifficulty,onBack,onLaunch}:{songs:MultiplayerSong[],profileLevel:number,playerId:string,displayName:string,initialDifficulty:MultiplayerDifficulty,onBack:()=>void,onLaunch:(launch:MultiplayerLaunch)=>void}){");
 code=replaceRequired(code,'account display name',"const [name,setName]=useState(()=>localStorage.getItem(DISPLAY_NAME_KEY)||'PLAYER'),","const [name]=useState(()=>displayName),");
 code=replaceRequired(code,'account player id',"const idRef=useRef(stablePlayerId()),","const idRef=useRef(playerId),");
 code=replaceFrom(code,'player-facing lobby',' if(roomCode)return',lobbyRender);
 return code;
};

const lobbyCss=`
/* Player-facing Online Battle presentation */
.multiplayer.battle-entry,.multiplayer.battle-room{background:radial-gradient(circle at 18% 2%,rgba(255,61,173,.2),transparent 32%),radial-gradient(circle at 82% 8%,rgba(41,242,255,.18),transparent 34%),radial-gradient(circle at 50% 82%,rgba(182,80,255,.14),transparent 36%),linear-gradient(180deg,#090611 0%,#050812 46%,#02040a 100%)}
.battle-entry header,.battle-room header{background:rgba(7,5,14,.76);border-bottom-color:rgba(255,255,255,.1)}
.battle-entry header>svg,.battle-room header>svg{justify-self:center;color:#ff3dad;filter:drop-shadow(0 0 12px rgba(255,61,173,.45))}
.battle-entry .mp-hero{position:relative;padding-top:44px}.battle-entry .mp-hero:before{content:"";position:absolute;left:50%;top:30px;width:min(520px,88vw);height:170px;transform:translateX(-50%);background:repeating-linear-gradient(90deg,transparent 0 11px,rgba(255,255,255,.035) 12px 14px);mask-image:linear-gradient(90deg,transparent,#000 18%,#000 82%,transparent);pointer-events:none}
.battle-entry .mp-hero-icon{position:relative;background:radial-gradient(circle,rgba(255,61,173,.34),rgba(41,242,255,.08) 54%,transparent 66%);box-shadow:0 0 55px rgba(255,61,173,.2)}.battle-entry .mp-hero-icon svg{color:#fff;filter:drop-shadow(0 0 10px rgba(41,242,255,.7))}
.battle-entry .mp-hero h1 i{background:linear-gradient(90deg,#ff3dad,#b650ff,#29f2ff);-webkit-background-clip:text;background-clip:text;color:transparent}.battle-entry .mp-hero p{color:#a8a0b9}
.mp-account-chip,.mp-account-note,.mp-history{width:min(720px,calc(100% - 32px));margin-left:auto;margin-right:auto}.mp-account-chip{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:12px;padding:13px 15px;border:1px solid rgba(255,255,255,.09);border-radius:18px;background:linear-gradient(135deg,rgba(255,61,173,.08),rgba(41,242,255,.055));box-shadow:0 12px 30px rgba(0,0,0,.18)}.mp-account-chip span{display:grid;gap:2px}.mp-account-chip span small{font-size:9px;letter-spacing:.16em;color:#8f86a2;font-weight:900}.mp-account-chip span strong{font-size:15px}.mp-account-chip em{font-style:normal;font-size:9px;font-weight:900;letter-spacing:.12em;color:#29f2ff;padding:7px 9px;border:1px solid rgba(41,242,255,.2);border-radius:999px;background:rgba(41,242,255,.07)}
.battle-entry .mp-actions{margin-top:14px}.battle-entry .mp-create{background:linear-gradient(100deg,#ff3dad,#8e45ff 52%,#29bdea);box-shadow:0 10px 30px rgba(182,80,255,.2)}.battle-entry .mp-divider{color:#827993}.battle-entry .mp-join input{background:rgba(13,9,23,.92);border-color:rgba(255,255,255,.11)}
.mp-history{margin-top:30px;padding:16px;border-radius:20px;border:1px solid rgba(255,255,255,.08);background:rgba(8,7,16,.72)}.mp-history-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:11px}.mp-history-title span{display:grid;gap:2px}.mp-history-title small{font-size:9px;letter-spacing:.16em;color:#8f86a2;font-weight:900}.mp-history-title strong{font-size:15px}.mp-history-title svg{width:20px;color:#ffd43b}.mp-history-row{display:grid;grid-template-columns:54px 1fr auto;align-items:center;gap:10px;padding:11px 0;border-top:1px solid rgba(255,255,255,.065)}.mp-history-row>.outcome{font-size:10px;letter-spacing:.09em}.mp-history-row>.outcome.win{color:#69ff9b}.mp-history-row>.outcome.loss{color:#ff6d82}.mp-history-row>.outcome.draw{color:#ffd43b}.mp-history-row>span{display:grid;gap:2px}.mp-history-row>span b{font-size:12px}.mp-history-row>span small,.mp-history-row>em small{font-size:9px;color:#776f89}.mp-history-row>em{font-style:normal;font-size:11px;font-weight:900;text-align:right;display:grid;gap:2px}.mp-history>p{margin:10px 0 2px;color:#756d84;font-size:12px}.mp-account-note{display:flex;gap:11px;align-items:center;margin-top:14px;padding:14px 15px;border-radius:16px;color:#8c84a0}.mp-account-note svg{width:19px;color:#b650ff}.mp-account-note span{display:grid;gap:2px}.mp-account-note strong{font-size:10px;letter-spacing:.08em;color:#cdc5da}.mp-account-note small{font-size:10px}
.battle-room .mp-room-code{grid-template-columns:1fr auto 46px;background:linear-gradient(110deg,rgba(255,61,173,.16),rgba(182,80,255,.12) 48%,rgba(41,242,255,.12));border-color:rgba(255,255,255,.13);box-shadow:0 12px 30px rgba(0,0,0,.22)}.battle-room .mp-room-code span{color:#a096b2}.battle-room .mp-room-code strong{background:linear-gradient(90deg,#fff,#ffb7df,#aeefff);-webkit-background-clip:text;background-clip:text;color:transparent}
.battle-room .mp-player-grid{position:relative}.battle-room .mp-player{background:linear-gradient(155deg,rgba(20,11,29,.94),rgba(6,11,20,.94));min-height:150px}.battle-room .mp-player.host.online{border-color:rgba(255,61,173,.35);box-shadow:inset 0 0 38px rgba(255,61,173,.045)}.battle-room .mp-player.challenger.online{border-color:rgba(41,242,255,.32);box-shadow:inset 0 0 38px rgba(41,242,255,.04)}.battle-room .mp-player.host .mp-avatar{color:#ff3dad;background:rgba(255,61,173,.1)}.battle-room .mp-player.challenger .mp-avatar{color:#29f2ff}.battle-room .mp-player span{color:#8a819a}.mp-versus{width:min(720px,calc(100% - 32px));margin:8px auto 0;display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center}.mp-versus span{height:1px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.16))}.mp-versus span:last-child{background:linear-gradient(90deg,rgba(255,255,255,.16),transparent)}.mp-versus strong{font-style:italic;font-size:12px;color:#ff7bc5;letter-spacing:.13em}
.battle-room .mp-panel{background:rgba(9,7,17,.82);border-color:rgba(255,255,255,.085)}.battle-room .mp-song-list button{background:linear-gradient(90deg,rgba(255,255,255,.035),rgba(255,255,255,.015));border-color:rgba(255,255,255,.075);position:relative;overflow:hidden}.battle-room .mp-song-list button:before{content:"";width:3px;align-self:stretch;border-radius:4px;background:#4d4658}.battle-room .mp-song-list button.active{border-color:rgba(255,61,173,.48);background:linear-gradient(90deg,rgba(255,61,173,.13),rgba(182,80,255,.07),rgba(41,242,255,.05))}.battle-room .mp-song-list button.active:before{background:linear-gradient(#ff3dad,#29f2ff);box-shadow:0 0 14px rgba(255,61,173,.5)}.battle-room .mp-song-list em{color:#b9aec8}.battle-room .mp-song-list button.active em{color:#ff9bd2}
.battle-room .mp-difficulty button.active{background:linear-gradient(120deg,rgba(255,61,173,.15),rgba(182,80,255,.12));border-color:rgba(255,61,173,.45)}.battle-room .mp-room-footer{background:linear-gradient(110deg,rgba(255,61,173,.065),rgba(41,242,255,.04));border-color:rgba(255,255,255,.09)}.battle-room .mp-room-footer>div:first-child svg{color:#ff3dad}.battle-room .mp-room-footer strong{font-size:11px}.battle-room .mp-room-footer small{color:#958ba7}.battle-room .mp-room-footer .primary{background:linear-gradient(100deg,#ff3dad,#9b49ff 55%,#29bdea)}
@media(max-width:540px){.mp-account-chip{grid-template-columns:auto 1fr}.mp-account-chip em{grid-column:2;justify-self:start}.mp-history-row{grid-template-columns:48px 1fr}.mp-history-row>em{grid-column:2;text-align:left}.battle-room .mp-player{min-height:132px}.battle-room .mp-song-list button{padding:11px 12px}.mp-account-note{align-items:flex-start}}
`;

export function battleExperienceTransform():Plugin{
 return {name:'rhythtap-battle-experience-transform',enforce:'pre',transform(source,id){const normalized=id.replaceAll('\\','/');if(normalized.endsWith('/src/main.tsx'))return{code:patchMain(source),map:null};if(normalized.endsWith('/src/player-account.tsx'))return{code:patchAccount(source),map:null};if(normalized.endsWith('/src/multiplayer-common.ts'))return{code:patchCommon(source),map:null};if(normalized.endsWith('/src/multiplayer-lobby.tsx'))return{code:patchLobby(source),map:null};if(normalized.endsWith('/src/multiplayer.css'))return{code:source+lobbyCss,map:null};return null}};
}
