from pathlib import Path

path=Path('scripts/stability-transform.ts')
text=path.read_text()
old=''' code=replaceRequired(code,'hold break scoring',\n  " const release=(lane:number)=>{pressed.current.delete(lane);const hold=activeHolds.current.get(lane);if(!hold)return;const remaining=hold.time+(hold.duration??0)-nowRef.current;if(remaining<=120){completeHold(lane);return}activeHolds.current.delete(lane);showFeedback('MISS',lane);setCombo(0);setEnergy(e=>Math.max(0,e-10))};",\n  " const release=(lane:number)=>{pressed.current.delete(lane);const hold=activeHolds.current.get(lane);if(!hold)return;const remaining=hold.time+(hold.duration??0)-nowRef.current;if(remaining<=120){completeHold(lane);return}activeHolds.current.delete(lane);const breakAt=Math.max(hold.time,nowRef.current);if(multiplayerSession.enabled)multiplayerSession.recordJudgement('HOLD_BREAK',hold.id,lane,breakAt);else soloEvents.current.push({kind:'HOLD_BREAK',noteId:hold.id,lane,atMs:Math.max(0,Math.round(breakAt))});applyJudge('MISS',lane)};");'''
new=''' code=replaceRequired(code,'hold break scoring',\n  " const release=(lane:number,eventTimeStamp?:number)=>{pressed.current.delete(lane);const hold=activeHolds.current.get(lane);if(!hold)return;const releaseTime=transport.current.now()-inputEventAgeMs(eventTimeStamp)+offset+(song.chartOffset||0),remaining=hold.time+(hold.duration??0)-releaseTime;if(remaining<=120){completeHold(lane);return}activeHolds.current.delete(lane);showFeedback('MISS',lane);setCombo(0);setEnergy(e=>Math.max(0,e-10))};",\n  " const release=(lane:number,eventTimeStamp?:number)=>{pressed.current.delete(lane);const hold=activeHolds.current.get(lane);if(!hold)return;const releaseTime=transport.current.now()-inputEventAgeMs(eventTimeStamp)+offset+(song.chartOffset||0),remaining=hold.time+(hold.duration??0)-releaseTime;if(remaining<=120){completeHold(lane);return}activeHolds.current.delete(lane);const breakAt=Math.max(hold.time,releaseTime);if(multiplayerSession.enabled)multiplayerSession.recordJudgement('HOLD_BREAK',hold.id,lane,breakAt);else soloEvents.current.push({kind:'HOLD_BREAK',noteId:hold.id,lane,atMs:Math.max(0,Math.round(breakAt))});applyJudge('MISS',lane)};");'''
assert old in text, 'hold break scoring block not found'
path.write_text(text.replace(old,new,1))
print('Updated stability transform for event-timestamped releases')
