import type {Plugin} from 'vite';
const required=(source:string,label:string,before:string,after:string)=>{if(!source.includes(before))throw new Error(`[gameplay-quality] Unable to patch ${label}; transformed layout changed.`);return source.replace(before,after)};
export function gameplayQualityTransform():Plugin{return{name:'rhythmtap-gameplay-quality-transform',enforce:'pre',transform(source,id){if(!id.replaceAll('\\','/').endsWith('/src/main.tsx'))return null;let code=source;
 code=required(code,'imports',"import {TourSetScreen,recordTourSetResult,getNextTourSetRun,tourSetPasses,type TourSetRun} from './tour-set-career';","import {TourSetScreen,recordTourSetResult,getNextTourSetRun,tourSetPasses,type TourSetRun} from './tour-set-career';\nimport {CalibrationScreen,loadCalibration,saveCalibration} from './gameplay-quality';");
 code=required(code,'screen type',"type Screen='home'|'select'|'library'|'leaderboard'|'multiplayer'|'account'|'publicProfile'|'tour'|'social'|'ranked'|'tutorial'|'game'|'results'|'settings'|'achievements';","type Screen='home'|'select'|'library'|'leaderboard'|'multiplayer'|'account'|'publicProfile'|'tour'|'social'|'ranked'|'tutorial'|'calibration'|'game'|'results'|'settings'|'achievements';");
 code=required(code,'offset loader',"[offset,setOffset]=useState(()=>Number(localStorage.getItem('ntr-offset')||0))","[offset,setOffset]=useState(loadCalibration)");
 code=required(code,'settings calibration callback',"replayTutorial={()=>{localStorage.removeItem('rhythtap-tutorial-seen');setScreen('game')}} back={()=>setScreen('home')}","replayTutorial={()=>{localStorage.removeItem('rhythtap-tutorial-seen');setScreen('tutorial')}} calibrate={()=>setScreen('calibration')} back={()=>setScreen('home')}");
 code=required(code,'calibration screen',"{screen==='achievements'&&<AchievementsScreen stats={stats} back={()=>setScreen('home')}/>}\n </main>","{screen==='achievements'&&<AchievementsScreen stats={stats} back={()=>setScreen('home')}/>}\n  {screen==='calibration'&&<CalibrationScreen offset={offset} setOffset={(value)=>{const next=saveCalibration(value);setOffset(next)}} back={()=>setScreen('settings')}/>}\n </main>");
 code=required(code,'settings signature',"function SettingsScreen({speed,setSpeed,offset,setOffset,profile,noteTheme,setNoteTheme,padTheme,setPadTheme,graphicsMode,setGraphicsMode,replayTutorial,back}:{speed:number,setSpeed:(n:number)=>void,offset:number,setOffset:(n:number)=>void,profile:Profile,noteTheme:NoteTheme,setNoteTheme:(v:NoteTheme)=>void,padTheme:PadTheme,setPadTheme:(v:PadTheme)=>void,graphicsMode:GraphicsMode,setGraphicsMode:(v:GraphicsMode)=>void,replayTutorial:()=>void,back:()=>void})","function SettingsScreen({speed,setSpeed,offset,setOffset,profile,noteTheme,setNoteTheme,padTheme,setPadTheme,graphicsMode,setGraphicsMode,replayTutorial,calibrate,back}:{speed:number,setSpeed:(n:number)=>void,offset:number,setOffset:(n:number)=>void,profile:Profile,noteTheme:NoteTheme,setNoteTheme:(v:NoteTheme)=>void,padTheme:PadTheme,setPadTheme:(v:PadTheme)=>void,graphicsMode:GraphicsMode,setGraphicsMode:(v:GraphicsMode)=>void,replayTutorial:()=>void,calibrate:()=>void,back:()=>void})");
 code=required(code,'settings button',"<div className=\"how\"><h3>HOW TO PLAY</h3>","<div className=\"how calibration-entry\"><h3>AUDIO CALIBRATION</h3><p>Correct speaker, Bluetooth, and browser latency on this device. Your current gameplay offset is <strong>{offset>0?'+':''}{offset} ms</strong>.</p><button className=\"tutorial-replay\" onClick={calibrate}><Headphones/> CALIBRATE TIMING</button></div>\n  <div className=\"how\"><h3>HOW TO PLAY</h3>");
 return{code,map:null}}}}
