import type {Plugin} from 'vite';

const replaceRequired=(source:string,label:string,before:string,after:string)=>{
 if(!source.includes(before))throw new Error(`[multiplayer] Unable to patch ${label}; source layout changed.`);
 return source.replace(before,after);
};

export function multiplayerTransform():Plugin{
 return {
  name:'rhythtap-multiplayer-transform',
  enforce:'pre',
  transform(source,id){
   if(!id.replaceAll('\\','/').endsWith('/src/main.tsx'))return null;
   let code=source;
   code=replaceRequired(code,'imports',"import './ux.css';","import './ux.css';\nimport {MultiplayerHud,MultiplayerLobby,MultiplayerResultOverlay,useMultiplayerSession,type MultiplayerLaunch,type MultiplayerSession} from './multiplayer';");
   code=replaceRequired(code,'screen type',"type Screen='home'|'select'|'library'|'leaderboard'|'game'|'results'|'settings'|'achievements';","type Screen='home'|'select'|'library'|'leaderboard'|'multiplayer'|'game'|'results'|'settings'|'achievements';");
   code=replaceRequired(code,'app multiplayer state'," const [result,setResult]=useState<GameResult>({score:0,accuracy:0,maxCombo:0,counts:{PERFECT:0,GREAT:0,GOOD:0,MISS:0},xpEarned:0,dailyBonus:0,levelUp:false,previousLevel:1});"," const [result,setResult]=useState<GameResult>({score:0,accuracy:0,maxCombo:0,counts:{PERFECT:0,GREAT:0,GOOD:0,MISS:0},xpEarned:0,dailyBonus:0,levelUp:false,previousLevel:1});\n const [multiplayerLaunch,setMultiplayerLaunch]=useState<MultiplayerLaunch|null>(null);\n const multiplayerSession=useMultiplayerSession(multiplayerLaunch,startAt=>{setMultiplayerLaunch(current=>current?{...current,startAt}:current);setScreen('game')});");
   code=replaceRequired(code,'home render',"{screen==='home'&&<Home profile={profile} stats={stats} onPlay={()=>setScreen('select')} onLibrary={()=>setScreen('library')} onAchievements={()=>setScreen('achievements')} onSettings={()=>setScreen('settings')}/>} ".trim(),"{screen==='home'&&<Home profile={profile} stats={stats} onPlay={()=>setScreen('select')} onMultiplayer={()=>setScreen('multiplayer')} onLibrary={()=>setScreen('library')} onAchievements={()=>setScreen('achievements')} onSettings={()=>setScreen('settings')}/>} ".trim());
   code=replaceRequired(code,'multiplayer screen',"  {screen==='leaderboard'&&<ChartLeaderboard songs={library.filter(item=>item.id.startsWith('tap-'))} difficulty={difficulty} setDifficulty={setDifficulty} back={()=>setScreen('library')}/>}\n  {screen==='game'&&<Game song={song} difficulty={difficulty} speed={speed} offset={offset} noteTheme={noteTheme} padTheme={padTheme} graphicsMode={graphicsMode} quit={()=>setScreen('select')} finish={finishGame}/>}","  {screen==='leaderboard'&&<ChartLeaderboard songs={library.filter(item=>item.id.startsWith('tap-'))} difficulty={difficulty} setDifficulty={setDifficulty} back={()=>setScreen('library')}/>}\n  {screen==='multiplayer'&&<MultiplayerLobby songs={library.filter(item=>!item.id.startsWith('tap-'))} profileLevel={profile.level} initialDifficulty={difficulty} onBack={()=>setScreen('home')} onLaunch={launch=>{const selected=library.find(item=>item.id===launch.songId);if(!selected)return;setSong(selected);setDifficulty(launch.difficulty);setMultiplayerLaunch(launch);setScreen('game')}}/>}\n  {screen==='game'&&<Game song={song} difficulty={difficulty} speed={speed} offset={offset} noteTheme={noteTheme} padTheme={padTheme} graphicsMode={graphicsMode} multiplayerSession={multiplayerSession} quit={()=>{if(multiplayerLaunch){setMultiplayerLaunch(null);setScreen('home')}else setScreen('select')}} finish={finishGame}/>}");
   code=replaceRequired(code,'results multiplayer',"  {screen==='results'&&<Results song={song} difficulty={difficulty} result={result} profile={profile} equipTheme={(theme)=>{setNoteTheme(theme);localStorage.setItem('rhythtap-note-theme',theme)}} retry={()=>setScreen('game')} done={()=>setScreen('select')}/>} ".trim(),"  {screen==='results'&&<><Results song={song} difficulty={difficulty} result={result} profile={profile} equipTheme={(theme)=>{setNoteTheme(theme);localStorage.setItem('rhythtap-note-theme',theme)}} retry={()=>multiplayerLaunch?multiplayerSession.requestRematch():setScreen('game')} done={()=>{if(multiplayerLaunch){setMultiplayerLaunch(null);setScreen('home')}else setScreen('select')}}/><MultiplayerResultOverlay session={multiplayerSession} localScore={result.score}/></>} ".trim());
   code=replaceRequired(code,'home signature',"function Home({profile,stats,onPlay,onLibrary,onAchievements,onSettings}:{profile:Profile,stats:Stats,onPlay:()=>void,onLibrary:()=>void,onAchievements:()=>void,onSettings:()=>void})","function Home({profile,stats,onPlay,onMultiplayer,onLibrary,onAchievements,onSettings}:{profile:Profile,stats:Stats,onPlay:()=>void,onMultiplayer:()=>void,onLibrary:()=>void,onAchievements:()=>void,onSettings:()=>void})");
   code=replaceRequired(code,'home multiplayer button',"<div className=\"quick-grid\"><button onClick={onLibrary}><span><Music2/></span><div><small>MY CHARTS</small><strong>Imported song library</strong></div><ChevronRight/></button><button onClick={onAchievements}><span><Trophy/></span><div><small>ACHIEVEMENTS</small><strong>{completedAchievements} / {achievements.length} earned</strong></div><ChevronRight/></button></div>","<div className=\"quick-grid\"><button onClick={onMultiplayer}><span><User/></span><div><small>ONLINE BATTLE</small><strong>2-player realtime score battle</strong></div><ChevronRight/></button><button onClick={onLibrary}><span><Music2/></span><div><small>MY CHARTS</small><strong>Imported song library</strong></div><ChevronRight/></button><button onClick={onAchievements}><span><Trophy/></span><div><small>ACHIEVEMENTS</small><strong>{completedAchievements} / {achievements.length} earned</strong></div><ChevronRight/></button></div>");
   code=replaceRequired(code,'game signature',"function Game({song,difficulty,speed,offset,noteTheme,padTheme,graphicsMode,quit,finish}:{song:Song,difficulty:Difficulty,speed:number,offset:number,noteTheme:NoteTheme,padTheme:PadTheme,graphicsMode:GraphicsMode,quit:()=>void,finish:(r:Omit<GameResult,'xpEarned'|'dailyBonus'|'levelUp'|'previousLevel'>)=>void})","function Game({song,difficulty,speed,offset,noteTheme,padTheme,graphicsMode,multiplayerSession,quit,finish}:{song:Song,difficulty:Difficulty,speed:number,offset:number,noteTheme:NoteTheme,padTheme:PadTheme,graphicsMode:GraphicsMode,multiplayerSession:MultiplayerSession,quit:()=>void,finish:(r:Omit<GameResult,'xpEarned'|'dailyBonus'|'levelUp'|'previousLevel'>)=>void})");
   code=replaceRequired(code,'tutorial bypass',"[showTutorial,setShowTutorial]=useState(()=>localStorage.getItem('rhythtap-tutorial-seen')!=='1')","[showTutorial,setShowTutorial]=useState(()=>!multiplayerSession.enabled&&localStorage.getItem('rhythtap-tutorial-seen')!=='1')");
   code=replaceRequired(code,'score publishing'," const scoreRef=useRef(score),comboRef=useRef(combo),countsRef=useRef(counts),maxRef=useRef(maxCombo);useEffect(()=>{scoreRef.current=score;comboRef.current=combo;countsRef.current=counts;maxRef.current=maxCombo},[score,combo,counts,maxCombo]);"," const scoreRef=useRef(score),comboRef=useRef(combo),countsRef=useRef(counts),maxRef=useRef(maxCombo);useEffect(()=>{scoreRef.current=score;comboRef.current=combo;countsRef.current=counts;maxRef.current=maxCombo},[score,combo,counts,maxCombo]);\n useEffect(()=>{if(!multiplayerSession.enabled)return;const total=Object.values(counts).reduce((a,b)=>a+b,0),weighted=counts.PERFECT+counts.GREAT*.8+counts.GOOD*.5;multiplayerSession.publishProgress({score,combo,accuracy:total?weighted/total*100:0})},[score,combo,counts,multiplayerSession.enabled,multiplayerSession.publishProgress]);");
   code=replaceRequired(code,'sync begin',"try{await transport.current.start(song);setReady(true)}catch","try{if(multiplayerSession.enabled&&multiplayerSession.launch){const wait=Math.max(0,multiplayerSession.launch.startAt-Date.now());if(wait>0)await new Promise(resolve=>setTimeout(resolve,wait))}await transport.current.start(song);if(multiplayerSession.enabled&&multiplayerSession.launch&&transport.current.media){const elapsed=Math.max(0,Date.now()-multiplayerSession.launch.startAt);if(elapsed>30)transport.current.media.currentTime=Math.min(transport.current.media.duration-.05,elapsed/1000)}setReady(true)}catch");
   code=replaceRequired(code,'auto multiplayer begin'," useEffect(()=>()=>{cancelAnimationFrame(raf.current);transport.current.stop()},[]);"," useEffect(()=>{if(multiplayerSession.enabled&&!ready&&!loading&&!showTutorial)void begin()},[multiplayerSession.enabled,showTutorial]);\n useEffect(()=>()=>{cancelAnimationFrame(raf.current);transport.current.stop()},[]);");
   code=replaceRequired(code,'final publish',"if(t>end){transport.current.stop();const c=countsRef.current,total=Object.values(c).reduce((a,b)=>a+b,0),weighted=c.PERFECT+c.GREAT*.8+c.GOOD*.5;finish({score:scoreRef.current,accuracy:total?weighted/total*100:0,maxCombo:maxRef.current,counts:c});return}","if(t>end){transport.current.stop();const c=countsRef.current,total=Object.values(c).reduce((a,b)=>a+b,0),weighted=c.PERFECT+c.GREAT*.8+c.GOOD*.5,finalResult={score:scoreRef.current,accuracy:total?weighted/total*100:0,maxCombo:maxRef.current,counts:c};if(multiplayerSession.enabled)multiplayerSession.publishFinal({score:finalResult.score,combo:finalResult.maxCombo,accuracy:finalResult.accuracy});finish(finalResult);return}");
   code=replaceRequired(code,'multiplayer hud',"  <GameplayMeters energy={energy} pulse={pulse}/>","  <GameplayMeters energy={energy} pulse={pulse}/>\n  <MultiplayerHud session={multiplayerSession}/>");
   return {code,map:null};
  }
 };
}
