import type {Plugin} from 'vite';

const replaceRequired=(source:string,label:string,before:string,after:string)=>{
 if(!source.includes(before))throw new Error(`[tour-set-career] Unable to patch ${label}; transformed layout changed.`);
 return source.replace(before,after);
};

export function tourSetCareerTransform():Plugin{
 return {name:'rhythtap-tour-set-career-transform',enforce:'pre',transform(source,id){
  if(!id.replaceAll('\\','/').endsWith('/src/main.tsx'))return null;
  let code=source;
  code=replaceRequired(code,'career imports',"import {TourScreen,SocialScreen,RankedScreen,recordTourResult,type TourRun} from './tour-social-ranked';","import {SocialScreen,RankedScreen} from './tour-social-ranked';\nimport {TourSetScreen,recordTourSetResult,getNextTourSetRun,type TourSetRun} from './tour-set-career';");
  code=replaceRequired(code,'career run type',"const [tourRun,setTourRun]=useState<TourRun|null>(null);","const [tourRun,setTourRun]=useState<TourSetRun|null>(null);");
  code=replaceRequired(code,'career result persistence',"recordTourResult(playerAccount.userId,tourRun,r.score,r.accuracy,difficulty)","recordTourSetResult(playerAccount.userId,tourRun,r.score,r.accuracy,difficulty)");
  code=replaceRequired(code,'career screen',"<TourScreen songs={library} profileLevel={profile.level} userId={playerAccount.userId} back={()=>setScreen('home')} onPlay={(songId,nextDifficulty,run)=>{const selected=library.find(item=>item.id===songId);if(!selected)return;setSong(selected);setDifficulty(nextDifficulty);setTourRun(run);setMultiplayerLaunch(null);setScreen('game')}}/>","<TourSetScreen songs={library} profileLevel={profile.level} userId={playerAccount.userId} back={()=>setScreen('home')} onPlay={(songId,nextDifficulty,run)=>{const selected=library.find(item=>item.id===songId);if(!selected)return;setSong(selected);setDifficulty(nextDifficulty);setTourRun(run);setMultiplayerLaunch(null);setScreen('game')}}/>");
  code=replaceRequired(code,'career results action',"battle={Boolean(multiplayerLaunch)} done={()=>{if(multiplayerLaunch){setMultiplayerResume(null);setMultiplayerLaunch(null);setScreen('home')}else if(tourRun){setTourRun(null);setScreen('tour')}else setScreen('select')}}","tourAction={tourRun?(result.accuracy<70?'BACK TO TOUR':tourRun.slot<2?'NEXT SONG':'FINISH SET'):undefined} battle={Boolean(multiplayerLaunch)} done={()=>{if(multiplayerLaunch){setMultiplayerResume(null);setMultiplayerLaunch(null);setScreen('home')}else if(tourRun){if(result.accuracy>=70){const next=getNextTourSetRun(tourRun);if(next){const selected=library.find(item=>item.id===next.songId);if(selected){setSong(selected);setDifficulty(next.difficulty);setTourRun(next.run);setScreen('game');return}}}setTourRun(null);setScreen('tour')}else setScreen('select')}}");
  code=replaceRequired(code,'results tour action prop',"function Results({song,difficulty,result,profile,equipTheme,retry,changeSong,battle=false,done}:{song:Song,difficulty:Difficulty,result:GameResult,profile:Profile,equipTheme:(theme:NoteTheme)=>void,retry:()=>void,changeSong?:()=>void,battle?:boolean,done:()=>void}){","function Results({song,difficulty,result,profile,equipTheme,retry,changeSong,tourAction,battle=false,done}:{song:Song,difficulty:Difficulty,result:GameResult,profile:Profile,equipTheme:(theme:NoteTheme)=>void,retry:()=>void,changeSong?:()=>void,tourAction?:string,battle?:boolean,done:()=>void}){");
  code=replaceRequired(code,'results career label','<div className="result-actions">{battle?<><button className="primary" onClick={retry}><RotateCcw/> REMATCH</button><button className="secondary" onClick={()=>changeSong?.()}><Music2/> CHANGE SONG</button><button className="secondary battle-leave" onClick={done}><ArrowLeft/> LEAVE BATTLE</button></>:<><button className="primary" onClick={retry}><RotateCcw/> RETRY</button><button className="secondary" onClick={done}>TRACK SELECT</button></>}</div>','<div className="result-actions">{battle?<><button className="primary" onClick={retry}><RotateCcw/> REMATCH</button><button className="secondary" onClick={()=>changeSong?.()}><Music2/> CHANGE SONG</button><button className="secondary battle-leave" onClick={done}><ArrowLeft/> LEAVE BATTLE</button></>:<><button className="primary" onClick={retry}><RotateCcw/> RETRY</button><button className="secondary" onClick={done}>{tourAction||\'TRACK SELECT\'}</button></>}</div>');
  code=replaceRequired(code,'tour home promise','<em>Start small. Earn stars. Unlock bigger gigs. Become the headliner.</em>','<em>Play full 3-song sets. Earn stars. Clear venues. Become the headliner.</em>');
  return {code,map:null};
 }};
}
