import type {Plugin} from 'vite';

const importAnchor="import {flyEagleEvents,neverLeftEvents,sicknessEvents,type OnsetEvent} from './audioChartData';";
const sharedImport="import {makeWeightedBeatChart,makeWeightedOnsetChart} from '../supabase/functions/_shared/weighted-chart-v4';";
const beforeBeat="const makeBeatChart=(bpm:number,offset:number,duration:number,difficulty:Difficulty,seed:number):Note[]=>{const beat=60000/bpm,step=difficulty==='EASY'?beat:beat/2,out:Note[]=[];let id=0,n=0;for(let time=offset;time<duration*1000-700;time+=step,n++){const lane=(n*2+Math.floor(n/4)+seed)%3;out.push({id:id++,time,lane,duration:n%32===20?beat*(difficulty==='EASY'?1:1.5):undefined});if(difficulty!=='EASY'&&n%8===0)out.push({id:id++,time,lane:(lane+1)%3});if(difficulty==='HARD'&&n%4===3)out.push({id:id++,time:time+step/2,lane:(lane+2+seed)%3})}return out};";
const afterBeat="const makeBeatChart=(bpm:number,offset:number,duration:number,difficulty:Difficulty,seed:number):Note[]=>makeWeightedBeatChart(bpm,offset,duration,difficulty,seed) as Note[];";
const beforeOnset="const makeOnsetChart=(events:readonly OnsetEvent[],difficulty:Difficulty):Note[]=>{const threshold={EASY:72,NORMAL:46,HARD:20}[difficulty],gap={EASY:330,NORMAL:170,HARD:85}[difficulty],out:Note[]=[];let id=0,last=-Infinity;for(let i=0;i<events.length;i++){const [time,sourceLane,strength]=events[i],lane=sourceLane%3;if(strength<threshold||time-last<gap)continue;const next=events[i+1]?.[0]??time;out.push({id:id++,time,lane,duration:strength>88&&next-time>650?Math.min(1200,(next-time)*.62):undefined});if(difficulty==='NORMAL'&&strength>88)out.push({id:id++,time,lane:(lane+1)%3});if(difficulty==='HARD'&&strength>70)out.push({id:id++,time,lane:(lane+2)%3});last=time}return out};";
const afterOnset="const makeOnsetChart=(events:readonly OnsetEvent[],difficulty:Difficulty):Note[]=>makeWeightedOnsetChart(events,difficulty) as Note[];";

export function weightedChartTransform():Plugin{return{name:'rhythtap-weighted-chart-transform',enforce:'pre',transform(source,id){if(!id.replaceAll('\\','/').endsWith('/src/main.tsx'))return null;if(!source.includes(importAnchor)||!source.includes(beforeBeat)||!source.includes(beforeOnset))throw new Error('[weighted-chart] chart generator source changed');return{code:source.replace(importAnchor,importAnchor+'\n'+sharedImport).replace(beforeBeat,afterBeat).replace(beforeOnset,afterOnset),map:null}}}};
