import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,Check,Headphones,RotateCcw,Target,Volume2} from 'lucide-react';
import {clampCalibration,suggestedCalibration} from './gameplay-timing';
import './gameplay-quality.css';

export const CALIBRATION_KEY='rhythtap-calibration-offset-v1';
export const loadCalibration=()=>clampCalibration(Number(localStorage.getItem(CALIBRATION_KEY)||localStorage.getItem('ntr-offset')||0));
export const saveCalibration=(value:number)=>{const next=clampCalibration(value);localStorage.setItem(CALIBRATION_KEY,String(next));localStorage.setItem('ntr-offset',String(next));return next};

export function CalibrationScreen({offset,setOffset,back}:{offset:number,setOffset:(value:number)=>void,back:()=>void}){
 const [running,setRunning]=useState(false),[samples,setSamples]=useState<number[]>([]),[flash,setFlash]=useState(false),[status,setStatus]=useState('Tap with the click, not the animation.'),ctx=useRef<AudioContext|null>(null),timer=useRef<number|undefined>(undefined),nextBeat=useRef(0),beatIndex=useRef(0),firstBeat=useRef(0),lastSampledBeat=useRef(-1);
 const suggested=useMemo(()=>suggestedCalibration(samples),[samples]);
 const stop=()=>{setRunning(false);if(timer.current)clearInterval(timer.current);timer.current=undefined;ctx.current?.close();ctx.current=null;setFlash(false)};
 useEffect(()=>stop,[]);
 const start=async()=>{stop();const audio=new AudioContext();ctx.current=audio;await audio.resume();setSamples([]);setStatus('Listen for the click and tap the large pad.');setRunning(true);beatIndex.current=0;lastSampledBeat.current=-1;firstBeat.current=audio.currentTime+.8;nextBeat.current=firstBeat.current;const schedule=()=>{if(!ctx.current)return;while(nextBeat.current<ctx.current.currentTime+.12){const when=nextBeat.current,index=beatIndex.current++;const osc=ctx.current.createOscillator(),gain=ctx.current.createGain();osc.frequency.value=index%4===0?1000:760;gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(.22,when+.002);gain.gain.exponentialRampToValueAtTime(.0001,when+.055);osc.connect(gain).connect(ctx.current.destination);osc.start(when);osc.stop(when+.06);const delay=Math.max(0,(when-ctx.current.currentTime)*1000);window.setTimeout(()=>{setFlash(true);window.setTimeout(()=>setFlash(false),70)},delay);nextBeat.current+=.5}};schedule();timer.current=window.setInterval(schedule,45)};
 const tap=()=>{if(!running||!ctx.current)return;const now=ctx.current.currentTime;if(now<firstBeat.current)return;const index=Math.floor((now-firstBeat.current)/.5);if(index<0||index===lastSampledBeat.current)return;const beatAt=firstBeat.current+index*.5,delta=(now-beatAt)*1000;if(delta<0||delta>240)return;lastSampledBeat.current=index;setSamples(current=>{const next=[...current,delta].slice(-12);if(next.length>=8)setStatus('Enough samples collected. Apply the suggested offset or keep tapping.');return next})};
 const apply=()=>{if(samples.length<8)return;const value=saveCalibration(suggested);setOffset(value);setStatus(`Saved ${value>0?'+':''}${value} ms on this device.`);stop()};
 const reset=()=>{setSamples([]);lastSampledBeat.current=-1;const value=saveCalibration(0);setOffset(value);setStatus('Calibration reset to 0 ms.')};
 return <section className="calibration-page screen"><header><button className="icon" onClick={()=>{stop();back()}} aria-label="Back"><ArrowLeft/></button><div><small>GAMEPLAY QUALITY</small><h2>AUDIO CALIBRATION</h2></div><span className="calibration-value">{offset>0?'+':''}{offset} ms</span></header><div className="calibration-copy"><Headphones/><div><strong>SYNC THIS DEVICE</strong><p>Bluetooth, speakers and browsers can add delay. RhythmTap stores this correction only on this device.</p></div></div><div className={'calibration-stage '+(flash?'beat':'')}><div className="calibration-pulse"><i/><b/></div><button className="calibration-pad" disabled={!running} onPointerDown={event=>{event.preventDefault();tap()}}><Target/><strong>{running?'TAP WITH THE CLICK':'START THE TEST'}</strong></button></div><div className="calibration-status"><span>{status}</span><small>{Math.min(samples.length,8)}/8 minimum taps</small></div><div className="calibration-readout"><div><small>CURRENT</small><strong>{offset>0?'+':''}{offset} ms</strong></div><div><small>SUGGESTED</small><strong>{samples.length>=8?(suggested>0?'+':'')+suggested+' ms':'—'}</strong></div></div><div className="calibration-actions">{!running?<button className="primary" onClick={()=>void start()}><Volume2/> START CLICK TEST</button>:<button className="secondary" onClick={stop}>STOP TEST</button>}<button className="primary" disabled={samples.length<8} onClick={apply}><Check/> APPLY SUGGESTED</button><button className="secondary" onClick={reset}><RotateCcw/> RESET TO 0 ms</button></div><div className="calibration-help"><strong>Manual fine tuning</strong><p>If notes still feel late, move the offset toward positive values. If they feel early, move it negative.</p><input aria-label="Manual calibration offset" type="range" min="-300" max="300" step="5" value={offset} onChange={event=>{const value=saveCalibration(Number(event.target.value));setOffset(value)}}/><div><span>-300 ms</span><span>0</span><span>+300 ms</span></div></div></section>
}
