import React, {memo, useCallback, useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, Award, Check, ChevronRight, Coins, FileUp, Gauge, Headphones, Music2, Pause, Play, RotateCcw, Settings, Sparkles, Square, Target, Trash2, Trophy, User, Volume2, Zap} from 'lucide-react';
import {flyEagleEvents,neverLeftEvents,sicknessEvents,type OnsetEvent} from './audioChartData';
import {parseTapChart} from './tapChart';
import './styles.css';
import './ux.css';

type Note={id:number,time:number,lane:number,duration?:number};
type Difficulty='EASY'|'NORMAL'|'HARD';
type Song={id:string,title:string,artist:string,bpm:number,color:string,root:number,progression:number[],melody:number[],unlockLevel:number,duration:number,audioFile?:string,previewFile?:string,localAudio?:boolean,audioName?:string,chartOffset?:number,charts:Record<Difficulty,Note[]>};
type Profile={xp:number,level:number};
type Stats={songsCompleted:number,perfectHits:number,bestCombo:number,dailyDate:string,dailyPlays:number,dailyClaimedDate:string};
type GameResult={score:number,accuracy:number,maxCombo:number,counts:Record<Judge,number>,xpEarned:number,dailyBonus:number,levelUp:boolean,previousLevel:number};
type Screen='home'|'select'|'library'|'leaderboard'|'game'|'results'|'settings'|'achievements';
type Judge='PERFECT'|'GREAT'|'GOOD'|'MISS';
type Feedback=Judge|'HOLD';
type NoteTheme='ORB'|'DIAMOND'|'HEX';
type PadTheme='CORE'|'RING'|'PRISM';
type GraphicsMode='FULL'|'LOW';
const LANES=['D','F','J'];
const COLORS=['#29f2ff','#b650ff','#ff3dad'];
const TIMING={perfect:55,great:110,good:220};
const lowerBoundNotes=(notes:Note[],time:number)=>{let low=0,high=notes.length;while(low<high){const middle=(low+high)>>>1;if(notes[middle].time<time)low=middle+1;else high=middle}return low};
const notesInWindow=(notes:Note[],start:number,end:number)=>notes.slice(lowerBoundNotes(notes,start),lowerBoundNotes(notes,end));
const laneFor=(pitch:number,melody:number[])=>{const low=Math.min(...melody),high=Math.max(...melody);return Math.max(0,Math.min(2,Math.round((pitch-low)/Math.max(1,high-low)*2)))};
const makeMelodyChart=(bpm:number,melody:number[],difficulty:Difficulty,bars=20):Note[]=>{
 const step=30000/bpm,out:Note[]=[];let id=0;
 for(let n=0;n<bars*8;n++){
  if(difficulty==='EASY'&&n%2)continue;
  const pitch=melody[n%melody.length],lane=laneFor(pitch,melody),next=melody[(n+1)%melody.length];
  out.push({id:id++,time:1800+n*step,lane,duration:next===pitch?step*.9:undefined});
  if(difficulty!=='EASY'&&n%8===0)out.push({id:id++,time:1800+n*step,lane:(lane+1)%3});
  if(difficulty==='HARD'&&n%8===4)out.push({id:id++,time:1800+n*step,lane:(lane+2)%3});
 }
 return out;
};
const charts=(bpm:number,melody:number[]):Record<Difficulty,Note[]>=>({EASY:makeMelodyChart(bpm,melody,'EASY'),NORMAL:makeMelodyChart(bpm,melody,'NORMAL'),HARD:makeMelodyChart(bpm,melody,'HARD')});
const makeBeatChart=(bpm:number,offset:number,duration:number,difficulty:Difficulty,seed:number):Note[]=>{const beat=60000/bpm,step=difficulty==='EASY'?beat:beat/2,out:Note[]=[];let id=0,n=0;for(let time=offset;time<duration*1000-700;time+=step,n++){const lane=(n*2+Math.floor(n/4)+seed)%3;out.push({id:id++,time,lane,duration:n%32===20?beat*(difficulty==='EASY'?1:1.5):undefined});if(difficulty!=='EASY'&&n%8===0)out.push({id:id++,time,lane:(lane+1)%3});if(difficulty==='HARD'&&n%4===3)out.push({id:id++,time:time+step/2,lane:(lane+2+seed)%3})}return out};
const beatCharts=(bpm:number,offset:number,duration:number,seed:number):Record<Difficulty,Note[]>=>({EASY:makeBeatChart(bpm,offset,duration,'EASY',seed),NORMAL:makeBeatChart(bpm,offset,duration,'NORMAL',seed),HARD:makeBeatChart(bpm,offset,duration,'HARD',seed)});
const makeOnsetChart=(events:readonly OnsetEvent[],difficulty:Difficulty):Note[]=>{const threshold={EASY:72,NORMAL:46,HARD:20}[difficulty],gap={EASY:330,NORMAL:170,HARD:85}[difficulty],out:Note[]=[];let id=0,last=-Infinity;for(let i=0;i<events.length;i++){const [time,sourceLane,strength]=events[i],lane=sourceLane%3;if(strength<threshold||time-last<gap)continue;const next=events[i+1]?.[0]??time;out.push({id:id++,time,lane,duration:strength>88&&next-time>650?Math.min(1200,(next-time)*.62):undefined});if(difficulty==='NORMAL'&&strength>88)out.push({id:id++,time,lane:(lane+1)%3});if(difficulty==='HARD'&&strength>70)out.push({id:id++,time,lane:(lane+2)%3});last=time}return out};
const onsetCharts=(events:readonly OnsetEvent[]):Record<Difficulty,Note[]>=>({EASY:makeOnsetChart(events,'EASY'),NORMAL:makeOnsetChart(events,'NORMAL'),HARD:makeOnsetChart(events,'HARD')});
const melodyVoltage=[12,15,19,17,12,10,7,10],melodyAfterglow=[12,14,15,19,17,15,14,10],melodyGravity=[12,19,17,15,14,10,12,7];
const baseSongs:Song[]=[
 {id:'voltage',title:'Midnight Voltage',artist:'NOVA//STATIC',bpm:118,color:'#22e8ff',root:45,progression:[0,5,3,7],melody:melodyVoltage,unlockLevel:1,duration:43,charts:charts(118,melodyVoltage)},
 {id:'afterglow',title:'Afterglow Circuit',artist:'Luma Driver',bpm:132,color:'#ff3dad',root:40,progression:[0,3,7,5],melody:melodyAfterglow,unlockLevel:2,duration:39,charts:charts(132,melodyAfterglow)},
 {id:'gravity',title:'Zero Gravity',artist:'Phase Garden',bpm:102,color:'#b650ff',root:43,progression:[0,7,5,3],melody:melodyGravity,unlockLevel:4,duration:49,charts:charts(102,melodyGravity)},
 {id:'sickness',title:'Down With the Sickness',artist:'Disturbed',bpm:95,color:'#9cff3d',root:0,progression:[],melody:[],unlockLevel:1,duration:217.704,audioFile:'audio/down-with-the-sickness.mp3',previewFile:'previews/sickness.mp3',charts:onsetCharts(sicknessEvents)},
 {id:'never-left',title:'If You Never Left',artist:'blink-182',bpm:195,color:'#ff704d',root:0,progression:[],melody:[],unlockLevel:1,duration:178.495,audioFile:'audio/if-you-never-left.mp3',previewFile:'previews/never-left.mp3',charts:onsetCharts(neverLeftEvents)},
 {id:'fly-eagle',title:'Fly Like an Eagle (Metal)',artist:'Licensed recording',bpm:105.4,color:'#ffd43b',root:0,progression:[],melody:[],unlockLevel:1,duration:192.192,audioFile:'audio/fly-like-an-eagle-metal.mp3',previewFile:'previews/fly-eagle.mp3',charts:onsetCharts(flyEagleEvents)}
];
const IMPORTED_SONGS_KEY='rhythtap-imported-songs';
const loadImportedSongs=():Song[]=>{try{const saved=JSON.parse(localStorage.getItem(IMPORTED_SONGS_KEY)||'[]');return Array.isArray(saved)?saved.filter(song=>song&&typeof song.id==='string'&&song.id.startsWith('tap-')&&Array.isArray(song.charts?.NORMAL)):[]}catch{return[]}};
const saveImportedSongs=(songs:Song[])=>localStorage.setItem(IMPORTED_SONGS_KEY,JSON.stringify(songs.filter(song=>song.id.startsWith('tap-'))));
const openAudioStore=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('rhythtap-audio',1);request.onupgradeneeded=()=>request.result.createObjectStore('tracks');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const storeAudio=async(id:string,file:File)=>{const db=await openAudioStore();await new Promise<void>((resolve,reject)=>{const transaction=db.transaction('tracks','readwrite');transaction.objectStore('tracks').put(file,id);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)});db.close()};
const getStoredAudio=async(id:string)=>{const db=await openAudioStore(),file=await new Promise<Blob|undefined>((resolve,reject)=>{const request=db.transaction('tracks').objectStore('tracks').get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return file};
const deleteStoredAudio=async(id:string)=>{const db=await openAudioStore();await new Promise<void>((resolve,reject)=>{const transaction=db.transaction('tracks','readwrite');transaction.objectStore('tracks').delete(id);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)});db.close()};
const highScoreFor=(songId:string,difficulty:Difficulty)=>Number(localStorage.getItem(`ntr-high-${songId}-${difficulty}`)||0);
const levelFor=(xp:number)=>Math.floor(Math.sqrt(xp/350))+1;
const xpFloor=(level:number)=>(level-1)*(level-1)*350;
const xpCeil=(level:number)=>level*level*350;
const loadProfile=():Profile=>{try{const saved=JSON.parse(localStorage.getItem('rhythtap-profile')||'{}');const xp=Math.max(0,Number(saved.xp)||0);return{xp,level:levelFor(xp)}}catch{return{xp:0,level:1}}};
const noteThemes:{id:NoteTheme,label:string,unlockLevel:number}[]=[{id:'ORB',label:'Orb',unlockLevel:1},{id:'DIAMOND',label:'Diamond',unlockLevel:2},{id:'HEX',label:'Hex',unlockLevel:4}];
const loadNoteTheme=():NoteTheme=>{const saved=localStorage.getItem('rhythtap-note-theme');return saved==='DIAMOND'||saved==='HEX'?saved:'ORB'};
const padThemes:{id:PadTheme,label:string,unlockLevel:number}[]=[{id:'CORE',label:'Core',unlockLevel:1},{id:'RING',label:'Pulse Ring',unlockLevel:3},{id:'PRISM',label:'Prism',unlockLevel:5}];
const loadPadTheme=():PadTheme=>{const saved=localStorage.getItem('rhythtap-pad-theme');return saved==='RING'||saved==='PRISM'?saved:'CORE'};
const prefersLowGraphics=()=>{const device=navigator as Navigator&{deviceMemory?:number},limitedMemory=device.deviceMemory!==undefined&&device.deviceMemory<=4,limitedCpu=device.hardwareConcurrency!==undefined&&device.hardwareConcurrency<=4,phoneLayout=matchMedia('(pointer: coarse) and (max-width: 768px)').matches;return limitedMemory||limitedCpu||phoneLayout};
const loadGraphicsMode=():GraphicsMode=>{const saved=localStorage.getItem('rhythtap-graphics');if(saved==='FULL'||saved==='LOW')return saved;return prefersLowGraphics()?'LOW':'FULL'};
const todayKey=()=>new Date().toISOString().slice(0,10);
const loadStats=():Stats=>{try{const saved=JSON.parse(localStorage.getItem('rhythtap-stats')||'{}'),today=todayKey();return{songsCompleted:Number(saved.songsCompleted)||0,perfectHits:Number(saved.perfectHits)||0,bestCombo:Number(saved.bestCombo)||0,dailyDate:today,dailyPlays:saved.dailyDate===today?Number(saved.dailyPlays)||0:0,dailyClaimedDate:String(saved.dailyClaimedDate||'')}}catch{return{songsCompleted:0,perfectHits:0,bestCombo:0,dailyDate:todayKey(),dailyPlays:0,dailyClaimedDate:''}}};
const achievements=[{id:'first-set',label:'First Set',detail:'Complete 1 track',target:1,value:(s:Stats)=>s.songsCompleted},{id:'combo-25',label:'Locked In',detail:'Reach a 25 combo',target:25,value:(s:Stats)=>s.bestCombo},{id:'perfect-100',label:'Perfect Pulse',detail:'Land 100 perfect hits',target:100,value:(s:Stats)=>s.perfectHits}];

class SynthTransport{
 ctx:AudioContext|null=null;source:AudioBufferSourceNode|null=null;media:HTMLAudioElement|null=null;objectUrl='';startAt=0;pausedAt=0;timer:number|undefined;song:Song|null=null;
 async playMedia(url:string,from=0,objectUrl=false){const media=new Audio(url);this.media=media;if(objectUrl)this.objectUrl=url;media.preload='auto';if(media.readyState<1)await new Promise<void>((resolve,reject)=>{const loaded=()=>{cleanup();resolve()},failed=()=>{cleanup();reject(new Error('Unable to load audio'))},cleanup=()=>{media.removeEventListener('loadedmetadata',loaded);media.removeEventListener('error',failed)};media.addEventListener('loadedmetadata',loaded,{once:true});media.addEventListener('error',failed,{once:true});media.load()});media.currentTime=Math.min(from/1000,Number.isFinite(media.duration)?Math.max(0,media.duration-.05):from/1000);await media.play();this.pausedAt=media.currentTime*1000}
 async start(song:Song,from=0){this.stop();this.song=song;if(song.localAudio){const file=await getStoredAudio(song.id);if(!file)throw new Error(`Audio missing for ${song.title}`);await this.playMedia(URL.createObjectURL(file),from,true);return}if(song.audioFile){await this.playMedia(import.meta.env.BASE_URL+song.audioFile,from);return}this.ctx=new AudioContext();await this.ctx.resume();this.startAt=this.ctx.currentTime-from/1000;this.schedule(song,from)}
 async preview(song:Song){this.stop();this.song=song;if(song.localAudio){const file=await getStoredAudio(song.id);if(!file)throw new Error(`Audio missing for ${song.title}`);await this.playMedia(URL.createObjectURL(file),0,true);return}if(song.previewFile){await this.playMedia(import.meta.env.BASE_URL+song.previewFile);return}this.ctx=new AudioContext();await this.ctx.resume();this.startAt=this.ctx.currentTime;this.schedule(song,0)}
 now(){return this.media?this.media.currentTime*1000:this.ctx?(this.ctx.currentTime-this.startAt)*1000:this.pausedAt}
 schedule(song:Song,from:number){if(!this.ctx)return;const ctx=this.ctx,step=30/song.bpm,leadIn=1.8;let n=Math.max(0,Math.floor((from/1000-leadIn)/step));const pump=()=>{if(!this.ctx)return;const horizon=(ctx.currentTime-this.startAt)+1.2;while(leadIn+n*step<horizon){const t=this.startAt+leadIn+n*step;if(t>ctx.currentTime){const bar=Math.floor(n/8),pos=n%8,root=song.root+song.progression[bar%song.progression.length],pitch=song.melody[n%song.melody.length];this.hat(t,pos%2?0.035:0.055);if(pos===0||pos===4)this.kick(t,pos===0?.34:.25);if(pos===2||pos===6)this.snare(t,.13);if(pos%2===0)this.tone(t,this.midi(root-12),step*.82,.12,'sawtooth',520);if(pos===0||pos===4)this.chord(t,root,step*3.4,.035);this.tone(t,this.midi(song.root+pitch),step*.72,pos%2?.042:.052,'square',1800)}n++}this.timer=window.setTimeout(pump,260)};pump()}
 midi(n:number){return 440*Math.pow(2,(n-69)/12)}
 tone(t:number,f:number,d:number,v:number,type:OscillatorType='triangle',cutoff=2200){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();o.type=type;o.frequency.setValueAtTime(f,t);filter.type='lowpass';filter.frequency.setValueAtTime(cutoff,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(filter).connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+d+.03)}
 chord(t:number,root:number,d:number,v:number){[0,3,7].forEach((x,i)=>this.tone(t,this.midi(root+x),d,v/(i+1),'sine',1400))}
 kick(t:number,v:number){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.frequency.setValueAtTime(145,t);o.frequency.exponentialRampToValueAtTime(46,t+.12);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+.2)}
 noise(t:number,d:number,v:number,highpass:number){if(!this.ctx)return;const length=Math.ceil(this.ctx.sampleRate*d),buffer=this.ctx.createBuffer(1,length,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=Math.random()*2-1;const source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),g=this.ctx.createGain();source.buffer=buffer;filter.type='highpass';filter.frequency.value=highpass;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);source.connect(filter).connect(g).connect(this.ctx.destination);source.start(t);source.stop(t+d)}
 snare(t:number,v:number){this.noise(t,.12,v,1100);this.tone(t,185,.08,v*.35,'triangle',800)}
 hat(t:number,v:number){this.noise(t,.045,v,6200)}
 pause(){this.pausedAt=this.now();if(this.media){this.media.pause();return}if(this.ctx)this.ctx.close();this.ctx=null;if(this.timer)clearTimeout(this.timer)}
 async resume(){if(this.media){await this.media.play();return}if(this.song)await this.start(this.song,this.pausedAt)}
 stop(){if(this.timer)clearTimeout(this.timer);try{this.source?.stop()}catch{}this.source=null;if(this.media){this.media.pause();this.media.removeAttribute('src');this.media.load();this.media=null}if(this.objectUrl){URL.revokeObjectURL(this.objectUrl);this.objectUrl=''}if(this.ctx)this.ctx.close();this.ctx=null}
}

function App(){
 const [screen,setScreen]=useState<Screen>('home'),[library,setLibrary]=useState<Song[]>(()=>[...baseSongs,...loadImportedSongs()]),[song,setSong]=useState(baseSongs[0]),[difficulty,setDifficulty]=useState<Difficulty>('NORMAL'),[profile,setProfile]=useState<Profile>(loadProfile),[stats,setStats]=useState<Stats>(loadStats),[speed,setSpeed]=useState(1),[offset,setOffset]=useState(()=>Number(localStorage.getItem('ntr-offset')||0)),[noteTheme,setNoteTheme]=useState<NoteTheme>(loadNoteTheme),[padTheme,setPadTheme]=useState<PadTheme>(loadPadTheme),[graphicsMode,setGraphicsMode]=useState<GraphicsMode>(loadGraphicsMode);
 const [result,setResult]=useState<GameResult>({score:0,accuracy:0,maxCombo:0,counts:{PERFECT:0,GREAT:0,GOOD:0,MISS:0},xpEarned:0,dailyBonus:0,levelUp:false,previousLevel:1});
 const importTap=async(file:File)=>{const imported=parseTapChart(await file.text()),notes=imported.notes as Note[],newSong:Song={id:'tap-'+imported.sourceId+'-'+Date.now(),title:imported.title,artist:imported.artist,bpm:120,color:'#69ff9b',root:43,progression:[0,5,3,7],melody:melodyVoltage,unlockLevel:1,duration:imported.duration,charts:{EASY:notes,NORMAL:notes,HARD:notes}};setLibrary(current=>{const next=[...current,newSong];saveImportedSongs(next);return next});setSong(newSong)};
 const attachAudio=async(id:string,file:File)=>{if(!file.type.startsWith('audio/'))throw new Error('Choose a valid audio file.');await storeAudio(id,file);setLibrary(current=>{const next=current.map(item=>item.id===id?{...item,localAudio:true,audioName:file.name}:item);saveImportedSongs(next);if(song.id===id)setSong(next.find(item=>item.id===id)!);return next})};
 const setChartOffset=(id:string,value:number)=>setLibrary(current=>{const next=current.map(item=>item.id===id?{...item,chartOffset:Math.max(-500,Math.min(500,value))}:item);saveImportedSongs(next);if(song.id===id)setSong(next.find(item=>item.id===id)!);return next});
 const removeImported=(id:string)=>{void deleteStoredAudio(id);setLibrary(current=>{const next=current.filter(item=>item.id!==id);saveImportedSongs(next);if(song.id===id)setSong(baseSongs[0]);return next})};
 const finishGame=(r:Omit<GameResult,'xpEarned'|'dailyBonus'|'levelUp'|'previousLevel'>)=>{const today=todayKey(),dailyPlays=(stats.dailyDate===today?stats.dailyPlays:0)+1,dailyBonus=dailyPlays>=2&&stats.dailyClaimedDate!==today?100:0,nextStats={songsCompleted:stats.songsCompleted+1,perfectHits:stats.perfectHits+r.counts.PERFECT,bestCombo:Math.max(stats.bestCombo,r.maxCombo),dailyDate:today,dailyPlays,dailyClaimedDate:dailyBonus?today:stats.dailyClaimedDate},multiplier={EASY:1,NORMAL:1.4,HARD:1.9}[difficulty],xpEarned=Math.max(25,Math.round((r.accuracy*1.8+r.score/850)*multiplier))+dailyBonus,xp=profile.xp+xpEarned,level=levelFor(xp),previousLevel=profile.level;setStats(nextStats);localStorage.setItem('rhythtap-stats',JSON.stringify(nextStats));setProfile({xp,level});localStorage.setItem('rhythtap-profile',JSON.stringify({xp}));setResult({...r,xpEarned,dailyBonus,levelUp:level>previousLevel,previousLevel});setScreen('results')};
 return <main>
  {screen==='home'&&<Home profile={profile} stats={stats} onPlay={()=>setScreen('select')} onLibrary={()=>setScreen('library')} onAchievements={()=>setScreen('achievements')} onSettings={()=>setScreen('settings')}/>}
  {screen==='select'&&<Select songs={library} song={song} setSong={setSong} difficulty={difficulty} setDifficulty={setDifficulty} profile={profile} noteTheme={noteTheme} importTap={importTap} back={()=>setScreen('home')} play={()=>setScreen('game')} />}
  {screen==='library'&&<ImportedLibrary songs={library.filter(item=>item.id.startsWith('tap-'))} difficulty={difficulty} setDifficulty={setDifficulty} importTap={importTap} attachAudio={attachAudio} setChartOffset={setChartOffset} removeSong={removeImported} scores={()=>setScreen('leaderboard')} back={()=>setScreen('home')} play={selected=>{setSong(selected);setScreen('game')}}/>}
  {screen==='leaderboard'&&<ChartLeaderboard songs={library.filter(item=>item.id.startsWith('tap-'))} difficulty={difficulty} setDifficulty={setDifficulty} back={()=>setScreen('library')}/>}
  {screen==='game'&&<Game song={song} difficulty={difficulty} speed={speed} offset={offset} noteTheme={noteTheme} padTheme={padTheme} graphicsMode={graphicsMode} quit={()=>setScreen('select')} finish={finishGame}/>}
  {screen==='results'&&<Results song={song} difficulty={difficulty} result={result} profile={profile} equipTheme={(theme)=>{setNoteTheme(theme);localStorage.setItem('rhythtap-note-theme',theme)}} retry={()=>setScreen('game')} done={()=>setScreen('select')}/>}
  {screen==='settings'&&<SettingsScreen
   speed={speed} setSpeed={setSpeed}
   offset={offset} setOffset={(v)=>{setOffset(v);localStorage.setItem('ntr-offset',String(v))}}
   profile={profile} noteTheme={noteTheme} setNoteTheme={(v)=>{setNoteTheme(v);localStorage.setItem('rhythtap-note-theme',v)}}
   padTheme={padTheme} setPadTheme={(v)=>{setPadTheme(v);localStorage.setItem('rhythtap-pad-theme',v)}}
   graphicsMode={graphicsMode} setGraphicsMode={(v)=>{setGraphicsMode(v);localStorage.setItem('rhythtap-graphics',v)}}
   replayTutorial={()=>{localStorage.removeItem('rhythtap-tutorial-seen');setScreen('game')}} back={()=>setScreen('home')}
  />}
  {screen==='achievements'&&<AchievementsScreen stats={stats} back={()=>setScreen('home')}/>}
 </main>
}

function Home({profile,stats,onPlay,onLibrary,onAchievements,onSettings}:{profile:Profile,stats:Stats,onPlay:()=>void,onLibrary:()=>void,onAchievements:()=>void,onSettings:()=>void}){const progress=(profile.xp-xpFloor(profile.level))/(xpCeil(profile.level)-xpFloor(profile.level))*100,dailyProgress=Math.min(2,stats.dailyPlays),completedAchievements=achievements.filter(a=>a.value(stats)>=a.target).length;return <section className="home screen">
 <div className="topbar"><span className="brandmark"><Zap fill="currentColor"/> RHYTHMTAP</span><div className="wallet"><Coins/> {Math.floor(profile.xp/10).toLocaleString()}</div><button className="icon" onClick={onSettings} aria-label="Settings"><Settings/></button></div>
 <div className="home-content"><div className="player-card"><div className="avatar"><User/></div><div className="player-copy"><small>WELCOME BACK</small><strong>PLAYER</strong><div className="xp-line"><span>LEVEL {profile.level}</span><span>{profile.xp-xpFloor(profile.level)} / {xpCeil(profile.level)-xpFloor(profile.level)} XP</span></div><div className="xp-track"><i style={{width:progress+'%'}}/></div></div></div>
 <div className="featured"><div className="featured-art"><span>LIVE SET</span><Music2/></div><div className="featured-copy"><div className="eyebrow">READY FOR YOUR NEXT SET?</div><h1>FEEL EVERY<br/><i>BEAT.</i></h1><p>Pick a track, lock in your difficulty, and chase a new high score.</p><button className="primary" onClick={onPlay}><Play fill="currentColor"/> PLAY NOW</button></div></div>
 <div className="quick-grid"><button onClick={onLibrary}><span><Music2/></span><div><small>MY CHARTS</small><strong>Imported song library</strong></div><ChevronRight/></button><button onClick={onAchievements}><span><Trophy/></span><div><small>ACHIEVEMENTS</small><strong>{completedAchievements} / {achievements.length} earned</strong></div><ChevronRight/></button></div>
 <div className={'daily '+(dailyProgress>=2?'complete':'')}><Target/><div><small>DAILY CHALLENGE</small><strong>{dailyProgress>=2?'Reward claimed · +100 XP':'Complete 2 tracks · +100 XP'}</strong><i><b style={{width:(dailyProgress/2*100)+'%'}}/></i></div><span>{dailyProgress}/2</span></div></div>
 </section>}

function Select({songs,song,setSong,difficulty,setDifficulty,profile,noteTheme,importTap,back,play}:{songs:Song[],song:Song,setSong:(s:Song)=>void,difficulty:Difficulty,setDifficulty:(d:Difficulty)=>void,profile:Profile,noteTheme:NoteTheme,importTap:(file:File)=>Promise<void>,back:()=>void,play:()=>void}){const preview=useRef(new SynthTransport()),[previewing,setPreviewing]=useState(''),[previewError,setPreviewError]=useState('');useEffect(()=>()=>preview.current.stop(),[]);const togglePreview=async(s:Song)=>{if(previewing===s.id){preview.current.stop();setPreviewing('');return}preview.current.stop();setSong(s);setPreviewError('');try{await preview.current.preview(s);setPreviewing(s.id);window.setTimeout(()=>setPreviewing(current=>{if(current===s.id){preview.current.stop();return ''}return current}),12000)}catch{setPreviewError('Preview unavailable');setPreviewing('')}};const importFile=async(file?:File)=>{if(!file)return;setPreviewError('');try{await importTap(file)}catch(error){setPreviewError(error instanceof Error?error.message:'Unable to import this .tap chart.')}};const leave=(next:()=>void)=>{preview.current.stop();next()};return <section className="select screen">
 <header><button className="icon" onClick={()=>leave(back)} aria-label="Back"><ArrowLeft/></button><div><small>SETLIST</small><h2>CHOOSE A TRACK</h2></div><span className="level">LEVEL {profile.level}</span></header>
 <div className="section-label"><span>YOUR SONGS</span><label className="tap-import"><FileUp/> IMPORT .TAP<input type="file" accept=".tap,text/plain" onChange={event=>{void importFile(event.target.files?.[0]);event.currentTarget.value=''}}/></label><small>{songs.length} TRACKS</small></div>
 <div className="songlist">{songs.map((s,i)=>{const locked=profile.level<s.unlockLevel;return <div key={s.id} className={'song '+(song.id===s.id?'active ':'')+(locked?'locked':'')} style={{'--song':s.color} as React.CSSProperties}>
  <button className="songpick" disabled={locked} onClick={()=>setSong(s)}><div className={'cover art-'+s.id}><div className="covergrid"/><b>{locked?'×':String(i+1).padStart(2,'0')}</b><i/></div><div className="songmeta"><span>{locked?`UNLOCKS AT LEVEL ${s.unlockLevel}`:s.artist}</span><h3>{s.title}</h3><div><em>{s.charts[difficulty].length} NOTES</em><span>{s.bpm} BPM</span></div></div></button><button className="preview" disabled={locked} onClick={()=>togglePreview(s)} aria-label={(previewing===s.id?'Stop ':'Preview ')+s.title}>{previewing===s.id?<Square fill="currentColor"/>:<Headphones/>}</button></div>})}</div>
 {previewError&&<div className="preview-error">{previewError}</div>}
 <div className="difficulty" aria-label="Difficulty">{(['EASY','NORMAL','HARD'] as Difficulty[]).map(d=><button key={d} className={difficulty===d?'active':''} onClick={()=>setDifficulty(d)}><span>{d}</span><small>{song.charts[d].length} NOTES</small></button>)}</div>
 <div className="playdock"><div className={'theme-preview theme-'+noteTheme.toLowerCase()} aria-label={(noteThemes.find(theme=>theme.id===noteTheme)?.label||'Orb')+' note theme preview'}>{COLORS.map((color,index)=><i key={color} style={{'--lane':color,'--delay':index} as React.CSSProperties}/>)}</div><div className="playdock-copy"><small>{difficulty} · {song.charts[difficulty].length} NOTES · {noteTheme}</small><strong>{song.title}</strong></div><button className="primary" onClick={()=>leave(play)}><Play fill="currentColor"/> PLAY</button></div>
 </section>}

const GameplayHud=memo(function GameplayHud({score,paused,quit,togglePause}:{score:number,paused:boolean,quit:()=>void,togglePause:()=>void}){return <div className="gamehud"><button className="icon" onClick={quit} aria-label="Exit track"><ArrowLeft/></button><div className="score"><small>SCORE</small><strong>{score.toString().padStart(7,'0')}</strong></div><button className="icon" onClick={togglePause} aria-label={paused?'Resume track':'Pause track'}>{paused?<Play/>:<Pause/>}</button></div>});
const GameplayMeters=memo(function GameplayMeters({energy,pulse}:{energy:number,pulse:number}){return <div className="meters"><div className="energy"><span style={{width:energy+'%'}}/></div><div className="pulse"><Zap size={14}/><span style={{width:pulse+'%'}}/></div></div>});
const GameplayFeedback=memo(function GameplayFeedback({judge,combo}:{judge:Feedback|null,combo:number}){return <div className="feedback" aria-live="polite" aria-atomic="true">{judge&&<strong className={judge.toLowerCase()}>{judge}</strong>}{combo>1&&<span>{combo}<small> COMBO</small></span>}</div>});

function GameplayTutorial({close,start}:{close:()=>void,start:()=>void}){const [step,setStep]=useState(0),steps=[{title:'TAP ON THE LINE',copy:'Tap a circular pad when its note reaches the bright judgment line.',visual:<div className="tutorial-lanes">{COLORS.map((color,index)=><i key={color} style={{'--lane':color,'--delay':index} as React.CSSProperties}/>)}</div>},{title:'HOLD LONG NOTES',copy:'Keep your finger down until the glowing tail reaches the line.',visual:<div className="tutorial-hold"><i/><b/></div>},{title:'BUILD YOUR COMBO',copy:'Accurate hits raise your multiplier. Pause anytime from the top-right button.',visual:<div className="tutorial-combo"><strong>12</strong><span>COMBO</span></div>}],current=steps[step];const finish=(play=false)=>{localStorage.setItem('rhythtap-tutorial-seen','1');close();if(play)start()};return <div className="tutorial" role="dialog" aria-modal="true" aria-labelledby="tutorial-title"><div className="tutorial-card"><div className="tutorial-progress" aria-label={'Tutorial step '+(step+1)+' of '+steps.length}>{steps.map((_,index)=><i key={index} className={index<=step?'active':''}/>)}</div><small>HOW TO PLAY · {step+1}/{steps.length}</small><div className="tutorial-visual">{current.visual}</div><h2 id="tutorial-title">{current.title}</h2><p>{current.copy}</p><button className="primary" onClick={()=>step<steps.length-1?setStep(value=>value+1):finish(true)}>{step<steps.length-1?'NEXT':'START PLAYING'} <ChevronRight/></button><button className="tutorial-skip" onClick={()=>finish()}>{step<steps.length-1?'SKIP TUTORIAL':'CLOSE'}</button></div></div>}

function Game({song,difficulty,speed,offset,noteTheme,padTheme,graphicsMode,quit,finish}:{song:Song,difficulty:Difficulty,speed:number,offset:number,noteTheme:NoteTheme,padTheme:PadTheme,graphicsMode:GraphicsMode,quit:()=>void,finish:(r:Omit<GameResult,'xpEarned'|'dailyBonus'|'levelUp'|'previousLevel'>)=>void}){
 const notes=song.charts[difficulty];
 const laneNotes=useMemo(()=>LANES.map((_,lane)=>notes.filter(note=>note.lane===lane)),[notes]);
 const phoneGameplay=useMemo(()=>matchMedia('(pointer: coarse) and (max-width: 430px)').matches,[]);
 const transport=useRef(new SynthTransport()),arenaRef=useRef<HTMLDivElement>(null),raf=useRef(0),pressed=useRef(new Set<number>()),judged=useRef(new Set<number>()),activeHolds=useRef(new Map<number,Note>()),feedbackTimer=useRef(0),nowRef=useRef(0),missCursor=useRef(0),lastPaint=useRef(0),frameHealth=useRef({last:0,samples:0,slow:0}),backgroundPaused=useRef(false);
 const [ready,setReady]=useState(false),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState(''),[showTutorial,setShowTutorial]=useState(()=>localStorage.getItem('rhythtap-tutorial-seen')!=='1'),[now,setNow]=useState(0),[arenaHeight,setArenaHeight]=useState(0),[paused,setPaused]=useState(false),[adaptiveLow,setAdaptiveLow]=useState(false),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[maxCombo,setMaxCombo]=useState(0),[judge,setJudge]=useState<Feedback|null>(null),[hitEffect,setHitEffect]=useState<{kind:Feedback,lane:number,id:number}|null>(null),[counts,setCounts]=useState({PERFECT:0,GREAT:0,GOOD:0,MISS:0}),[pulse,setPulse]=useState(0),[energy,setEnergy]=useState(100);
 const effectiveGraphicsMode:GraphicsMode=adaptiveLow?'LOW':graphicsMode;
 const scoreRef=useRef(score),comboRef=useRef(combo),countsRef=useRef(counts),maxRef=useRef(maxCombo);useEffect(()=>{scoreRef.current=score;comboRef.current=combo;countsRef.current=counts;maxRef.current=maxCombo},[score,combo,counts,maxCombo]);
 const end=notes.at(-1)!.time+2200;
 const showFeedback=(value:Feedback,lane=1)=>{setJudge(value);if(effectiveGraphicsMode==='FULL')setHitEffect({kind:value,lane,id:performance.now()});clearTimeout(feedbackTimer.current);feedbackTimer.current=window.setTimeout(()=>{setJudge(null);if(effectiveGraphicsMode==='FULL')setHitEffect(null)},360)};
 const begin=async()=>{judged.current.clear();activeHolds.current.clear();pressed.current.clear();missCursor.current=0;nowRef.current=0;lastPaint.current=0;frameHealth.current={last:0,samples:0,slow:0};backgroundPaused.current=false;setAdaptiveLow(false);setLoading(true);setLoadError('');try{await transport.current.start(song);setReady(true)}catch{setLoadError('The track could not be loaded. Check your connection and try again.')}finally{setLoading(false)}};
 useEffect(()=>()=>{cancelAnimationFrame(raf.current);transport.current.stop()},[]);
 useEffect(()=>{const arena=arenaRef.current;if(!arena)return;const measure=()=>setArenaHeight(arena.clientHeight);measure();const observer=new ResizeObserver(measure);observer.observe(arena);return()=>observer.disconnect()},[]);
 const applyJudge=(j:Judge,lane:number)=>{showFeedback(j,lane);setCounts(c=>({...c,[j]:c[j]+1}));if(j==='MISS'){setCombo(0);setEnergy(e=>Math.max(0,e-8));return}const base={PERFECT:1000,GREAT:700,GOOD:350,MISS:0}[j],multiplier=Math.min(4,1+Math.floor(comboRef.current/10));setScore(s=>s+base*multiplier);setCombo(c=>{const n=c+1;setMaxCombo(m=>Math.max(m,n));return n});setPulse(p=>Math.min(100,p+(j==='PERFECT'?5:2)));setEnergy(e=>Math.min(100,e+1))};
 const completeHold=(lane:number)=>{if(!activeHolds.current.has(lane))return;activeHolds.current.delete(lane);const multiplier=Math.min(4,1+Math.floor(comboRef.current/10));setScore(s=>s+600*multiplier);setPulse(p=>Math.min(100,p+8));setEnergy(e=>Math.min(100,e+3));showFeedback('HOLD',lane)};
 const release=(lane:number)=>{pressed.current.delete(lane);const hold=activeHolds.current.get(lane);if(!hold)return;const remaining=hold.time+(hold.duration??0)-nowRef.current;if(remaining<=120){completeHold(lane);return}activeHolds.current.delete(lane);showFeedback('MISS',lane);setCombo(0);setEnergy(e=>Math.max(0,e-10))};
 const hit=(lane:number)=>{if(!ready||paused)return;pressed.current.add(lane);if(activeHolds.current.has(lane))return;const hitTime=transport.current.now()+offset+(song.chartOffset||0),laneChart=laneNotes[lane],windowStart=hitTime-TIMING.good;nowRef.current=hitTime;let low=0,high=laneChart.length;while(low<high){const middle=(low+high)>>>1;if(laneChart[middle].time<windowStart)low=middle+1;else high=middle}let best:Note|undefined,dist=Infinity;for(let index=low;index<laneChart.length;index++){const n=laneChart[index];if(n.time>hitTime+TIMING.good)break;const d=Math.abs(hitTime-n.time);if(!judged.current.has(n.id)&&d<dist){best=n;dist=d}}if(!best)return;judged.current.add(best.id);if(best.duration)activeHolds.current.set(lane,best);applyJudge(dist<=TIMING.perfect?'PERFECT':dist<=TIMING.great?'GREAT':'GOOD',lane)};
 useEffect(()=>{if(!ready||paused)return;const paintInterval=effectiveGraphicsMode==='LOW'?(phoneGameplay?20:28):16,healthWindow=phoneGameplay?30:45,slowLimit=phoneGameplay?8:14,tick=(frameTime:number)=>{const health=frameHealth.current;if(health.last>0){const frameGap=frameTime-health.last;if(frameGap<250){health.samples++;if(frameGap>24)health.slow++}if(health.samples>=healthWindow){if(graphicsMode==='FULL'&&!adaptiveLow&&health.slow>=slowLimit)setAdaptiveLow(true);health.samples=0;health.slow=0}}health.last=frameTime;const t=transport.current.now()+offset+(song.chartOffset||0);nowRef.current=t;if(frameTime-lastPaint.current>=paintInterval){lastPaint.current=frameTime;setNow(t)}while(missCursor.current<notes.length&&t-notes[missCursor.current].time>TIMING.good){const n=notes[missCursor.current++];if(!judged.current.has(n.id)){judged.current.add(n.id);applyJudge('MISS',n.lane)}}for(const [lane,n] of activeHolds.current){const tail=n.time+(n.duration??0);if(pressed.current.has(lane)&&t>=tail-90)completeHold(lane)}if(t>end){transport.current.stop();const c=countsRef.current,total=Object.values(c).reduce((a,b)=>a+b,0),weighted=c.PERFECT+c.GREAT*.8+c.GOOD*.5;finish({score:scoreRef.current,accuracy:total?weighted/total*100:0,maxCombo:maxRef.current,counts:c});return}raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf.current)},[ready,paused,effectiveGraphicsMode,phoneGameplay]);
 useEffect(()=>{const handleVisibility=()=>{if(document.hidden&&ready&&!paused){backgroundPaused.current=true;pressed.current.clear();transport.current.pause();setPaused(true)}};document.addEventListener('visibilitychange',handleVisibility);return()=>document.removeEventListener('visibilitychange',handleVisibility)},[ready,paused]);
 useEffect(()=>{const keys=['KeyD','KeyF','KeyJ'],down=(e:KeyboardEvent)=>{const i=keys.indexOf(e.code);if(i>=0){e.preventDefault();if(!e.repeat)hit(i)}if(e.code==='Escape')togglePause()};const up=(e:KeyboardEvent)=>{const i=keys.indexOf(e.code);if(i>=0)release(i)};addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[ready,paused]);
 const togglePause=useCallback(async()=>{if(!ready)return;if(paused){await transport.current.resume();backgroundPaused.current=false;setPaused(false)}else{backgroundPaused.current=false;pressed.current.clear();transport.current.pause();setPaused(true)}},[ready,paused]);
 const travel=1800/speed,fullGraphics=effectiveGraphicsMode==='FULL',beatPosition=fullGraphics?(now/60000*song.bpm)%1:0,beatIntensity=fullGraphics&&ready&&!paused?Math.pow(Math.max(0,Math.cos(beatPosition*Math.PI*2)),8):0,beatScale=1+beatIntensity*.1;
 return <section className={'game screen theme-'+noteTheme.toLowerCase()+' pad-theme-'+padTheme.toLowerCase()+' graphics-'+effectiveGraphicsMode.toLowerCase()}><GameplayHud score={score} paused={paused} quit={quit} togglePause={togglePause}/>
  <GameplayMeters energy={energy} pulse={pulse}/>
  <div ref={arenaRef} className="arena" style={{'--beat':beatIntensity,'--song-color':song.color} as React.CSSProperties}>{LANES.map((k,l)=><div className={'lane '+(activeHolds.current.has(l)?'holding':'')} key={k} style={{'--lane':COLORS[l]} as React.CSSProperties}>{arenaHeight>0&&notesInWindow(laneNotes[l],now-travel*.25,now+travel*1.25).filter(n=>!judged.current.has(n.id)||activeHolds.current.get(l)?.id===n.id).map(n=>{const isActive=activeHolds.current.get(l)?.id===n.id,hitLineY=89,y=isActive?hitLineY:(now-(n.time-travel))/travel*hitLineY,noteScale=.92+Math.max(0,Math.min(1,y/hitLineY))*.2,tail=n.duration?Math.max(28,(n.time+n.duration-now)/travel*70):undefined;return y>-12&&y<105?<div key={n.id} className={'note '+(n.duration?'hold ':'')+(isActive?'active-hold':'')} style={{'--note-y':y/100*arenaHeight+'px','--note-scale':noteScale,height:n.duration?tail:undefined} as React.CSSProperties}>{fullGraphics&&<i/>}<b/></div>:null})}<button className="pad" aria-label={'Lane '+(l+1)+' · '+k} aria-pressed={activeHolds.current.has(l)} style={{'--beat-scale':beatScale} as React.CSSProperties} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);hit(l)}} onPointerUp={()=>release(l)} onPointerCancel={()=>release(l)}><span>{activeHolds.current.has(l)?'HOLD':k}</span></button></div>)}{fullGraphics&&hitEffect&&hitEffect.kind!=='MISS'&&<div key={hitEffect.id} className={'hit-burst '+hitEffect.kind.toLowerCase()} style={{left:'calc('+((hitEffect.lane+.5)/3*100)+'%)'}}>{Array.from({length:10},(_,i)=><i key={i} style={{'--angle':(i*36)+'deg'} as React.CSSProperties}/>)}</div>}</div>
  <GameplayFeedback judge={judge} combo={combo}/>
  {showTutorial&&<GameplayTutorial close={()=>setShowTutorial(false)} start={()=>{void begin()}}/>}
  {!ready&&<div className="modal"><Volume2/><h2>{loading?'LOADING TRACK':'READY TO SYNC?'}</h2><p>{loadError||'Turn up your sound. Notes are timed to the audio clock.'}</p><button className="primary" disabled={loading} onClick={begin}><Play fill="currentColor"/> {loading?'DECODING AUDIO…':'TAP TO START'}</button></div>}
  {paused&&<div className="modal"><Pause/><h2>PAUSED</h2>{backgroundPaused.current&&<p>Gameplay paused while RhythmTap was in the background.</p>}<button className="primary" onClick={togglePause}><Play/> RESUME</button><button className="secondary" onClick={quit}>EXIT TRACK</button></div>}
 </section>}

function Results({song,difficulty,result,profile,equipTheme,retry,done}:{song:Song,difficulty:Difficulty,result:GameResult,profile:Profile,equipTheme:(theme:NoteTheme)=>void,retry:()=>void,done:()=>void}){
 const grade=result.accuracy>=95?'S':result.accuracy>=88?'A':result.accuracy>=75?'B':'C',progress=(profile.xp-xpFloor(profile.level))/(xpCeil(profile.level)-xpFloor(profile.level))*100,newUnlocks=noteThemes.filter(theme=>theme.unlockLevel>result.previousLevel&&theme.unlockLevel<=profile.level),[previousBest]=useState(()=>highScoreFor(song.id,difficulty)),[unlockIndex,setUnlockIndex]=useState(newUnlocks.length?0:-1),unlocked=unlockIndex>=0?newUnlocks[unlockIndex]:undefined,isNewBest=result.score>previousBest,totalHits=Object.values(result.counts).reduce((sum,value)=>sum+value,0);
 useEffect(()=>{const key=`ntr-high-${song.id}-${difficulty}`;localStorage.setItem(key,String(Math.max(result.score,Number(localStorage.getItem(key)||0))))},[]);
 const closeUnlock=()=>setUnlockIndex(i=>i<newUnlocks.length-1?i+1:-1),equip=()=>{if(unlocked)equipTheme(unlocked.id);closeUnlock()};
 return <section className="results screen"><header className="results-header"><button className="icon" onClick={done} aria-label="Back to track select"><ArrowLeft/></button><div><small>{difficulty} · TRACK COMPLETE</small><h2>{song.title}</h2></div>{isNewBest?<span className="new-best"><Trophy/> NEW BEST</span>:<span className="level">LEVEL {profile.level}</span>}</header><div className="result-scroll"><div className="result-hero"><div className={'grade grade-'+grade.toLowerCase()}>{grade}</div><div className="result-score"><small>FINAL SCORE</small><strong>{result.score.toLocaleString()}</strong>{!isNewBest&&previousBest>0&&<span>BEST {previousBest.toLocaleString()}</span>}</div></div><div className="result-stats"><div><Target/><small>ACCURACY</small><strong>{result.accuracy.toFixed(1)}%</strong></div><div><Zap/><small>MAX COMBO</small><strong>{result.maxCombo}</strong></div><div><Music2/><small>TOTAL NOTES</small><strong>{totalHits}</strong></div></div><div className="breakdown" aria-label="Hit judgement breakdown">{Object.entries(result.counts).map(([key,value])=><div className={'judge-'+key.toLowerCase()} key={key}><i/><span>{key}</span><strong>{String(value)}</strong></div>)}</div><div className="xp-award"><div className="xp-award-heading"><span><small>{result.levelUp?'NEW LEVEL':'PERFORMANCE REWARD'}</small><strong>{result.levelUp?`LEVEL ${profile.level}`:`+${result.xpEarned} XP`}</strong></span><b>{Math.round(progress)}%</b></div>{result.dailyBonus>0&&<em>DAILY CHALLENGE COMPLETE · +{result.dailyBonus} XP</em>}<div><i style={{width:progress+'%'}}/></div><small>{profile.xp-xpFloor(profile.level)} / {xpCeil(profile.level)-xpFloor(profile.level)} XP TO NEXT LEVEL</small></div><div className="result-actions"><button className="primary" onClick={retry}><RotateCcw/> RETRY</button><button className="secondary" onClick={done}>TRACK SELECT</button></div></div>{unlocked&&<div className="unlock-reveal" role="dialog" aria-modal="true" aria-label={unlocked.label+' theme unlocked'}><div className="unlock-rays"/><div className="unlock-confetti">{Array.from({length:12},(_,i)=><i key={i} style={{'--piece':i} as React.CSSProperties}/>)}</div><div className="unlock-card"><Sparkles/><small>LEVEL {unlocked.unlockLevel} REWARD</small><h2>NEW THEME<br/>UNLOCKED</h2><div className={'unlock-shape '+unlocked.id.toLowerCase()}><i/></div><strong>{unlocked.label}</strong><p>A new note shape has been added to your collection.</p><button className="primary" onClick={equip}>EQUIP NOW</button><button className="unlock-later" onClick={closeUnlock}>{unlockIndex<newUnlocks.length-1?'NEXT REWARD':'KEEP CURRENT THEME'}</button></div></div>}</section>
}

function ImportedLibrary({songs,difficulty,setDifficulty,importTap,attachAudio,setChartOffset,removeSong,scores,back,play}:{songs:Song[],difficulty:Difficulty,setDifficulty:(value:Difficulty)=>void,importTap:(file:File)=>Promise<void>,attachAudio:(id:string,file:File)=>Promise<void>,setChartOffset:(id:string,value:number)=>void,removeSong:(id:string)=>void,scores:()=>void,back:()=>void,play:(song:Song)=>void}){const [message,setMessage]=useState('');const add=async(file?:File)=>{if(!file)return;setMessage('');try{await importTap(file);setMessage('Chart imported and saved on this device.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to import this .tap chart.')}};const pair=async(id:string,file?:File)=>{if(!file)return;setMessage('');try{await attachAudio(id,file);setMessage('Audio paired and saved on this device.')}catch(error){setMessage(error instanceof Error?error.message:'Unable to save this audio file.')}};return <section className="imported-library screen">
 <header><button className="icon" onClick={back} aria-label="Back"><ArrowLeft/></button><div><small>LOCAL COLLECTION</small><h2>MY TAP CHARTS</h2></div><button className="icon score-link" onClick={scores} aria-label="High scores"><Trophy/></button><span className="chart-count">{songs.length}</span></header>
 <div className="library-tools"><div><strong>IMPORTED SONGS</strong><small>Charts stay saved on this device</small></div><label className="library-import"><FileUp/> IMPORT .TAP<input type="file" accept=".tap,text/plain" onChange={event=>{void add(event.target.files?.[0]);event.currentTarget.value=''}}/></label></div>
 <div className="library-difficulty">{(['EASY','NORMAL','HARD'] as Difficulty[]).map(value=><button key={value} className={difficulty===value?'active':''} onClick={()=>setDifficulty(value)}>{value}</button>)}</div>
 {message&&<div className="library-message">{message}</div>}
 {songs.length===0?<div className="library-empty"><FileUp/><h3>NO IMPORTED CHARTS</h3><p>Import a Phoenix-style .tap file to add it to your permanent local song library.</p><label className="primary">CHOOSE .TAP FILE<input type="file" accept=".tap,text/plain" onChange={event=>{void add(event.target.files?.[0]);event.currentTarget.value=''}}/></label></div>:<div className="imported-list">{songs.map((item,index)=><article className="imported-card" key={item.id}><div className="imported-art"><span>{String(index+1).padStart(2,'0')}</span><Music2/></div><div className="imported-meta"><small>{item.artist}</small><h3>{item.title}</h3><span>{item.charts[difficulty].length} NOTES · BEST {highScoreFor(item.id,difficulty).toLocaleString()}</span><label className={'audio-pair '+(item.localAudio?'paired':'')}><Volume2/>{item.localAudio?(item.audioName||'AUDIO PAIRED'):'ADD AUDIO'}<input type="file" accept="audio/*,.mp3,.m4a,.wav,.ogg,.aac,.flac" onChange={event=>{void pair(item.id,event.target.files?.[0]);event.currentTarget.value=''}}/></label><div className="chart-sync"><small>CHART SYNC</small><button onClick={()=>setChartOffset(item.id,(item.chartOffset||0)-10)}>−10</button><strong>{item.chartOffset||0}ms</strong><button onClick={()=>setChartOffset(item.id,(item.chartOffset||0)+10)}>+10</button><button className="sync-reset" onClick={()=>setChartOffset(item.id,0)}>RESET</button></div></div><button className="imported-play" onClick={()=>play(item)} aria-label={'Play '+item.title}><Play fill="currentColor"/></button><button className="imported-delete" onClick={()=>removeSong(item.id)} aria-label={'Delete '+item.title}><Trash2/></button></article>)}</div>}
 </section>}

function ChartLeaderboard({songs,difficulty,setDifficulty,back}:{songs:Song[],difficulty:Difficulty,setDifficulty:(value:Difficulty)=>void,back:()=>void}){const ranked=[...songs].map(song=>({song,score:highScoreFor(song.id,difficulty)})).sort((a,b)=>b.score-a.score||a.song.title.localeCompare(b.song.title));return <section className="chart-leaderboard screen">
 <header><button className="icon" onClick={back} aria-label="Back"><ArrowLeft/></button><div><small>PERSONAL RECORDS</small><h2>HIGH SCORES</h2></div><Trophy className="leaderboard-trophy"/></header>
 <div className="library-difficulty">{(['EASY','NORMAL','HARD'] as Difficulty[]).map(value=><button key={value} className={difficulty===value?'active':''} onClick={()=>setDifficulty(value)}>{value}</button>)}</div>
 <div className="leaderboard-summary"><Trophy/><div><small>{difficulty} CHARTS</small><strong>{ranked.length} RANKED</strong></div><span>{ranked.reduce((best,item)=>Math.max(best,item.score),0).toLocaleString()}<small> TOP SCORE</small></span></div>
 {ranked.length===0?<div className="library-empty"><Trophy/><h3>NO SCORES YET</h3><p>Import a chart and complete a track to start your personal leaderboard.</p></div>:<div className="leaderboard-list">{ranked.map((item,index)=><article className={'leaderboard-row rank-'+(index+1)} key={item.song.id}><strong className="rank">{String(index+1).padStart(2,'0')}</strong><div><small>{item.song.artist}</small><h3>{item.song.title}</h3><span>{item.song.charts[difficulty].length} NOTES</span></div><strong className="record">{item.score.toLocaleString()}<small>PTS</small></strong></article>)}</div>}
 </section>}

function SettingsScreen({speed,setSpeed,offset,setOffset,profile,noteTheme,setNoteTheme,padTheme,setPadTheme,graphicsMode,setGraphicsMode,replayTutorial,back}:{speed:number,setSpeed:(n:number)=>void,offset:number,setOffset:(n:number)=>void,profile:Profile,noteTheme:NoteTheme,setNoteTheme:(v:NoteTheme)=>void,padTheme:PadTheme,setPadTheme:(v:PadTheme)=>void,graphicsMode:GraphicsMode,setGraphicsMode:(v:GraphicsMode)=>void,replayTutorial:()=>void,back:()=>void}){
 return <section className="settingsPage screen">
  <header><button className="icon" onClick={back} aria-label="Back"><ArrowLeft/></button><div><small>SYSTEM</small><h2>SETTINGS</h2></div></header>
  <div className="setting"><div><Gauge/><span><strong>NOTE SPEED</strong><small>How quickly notes cross the playfield</small></span></div><output>{speed.toFixed(1)}×</output><input type="range" min="0.7" max="1.5" step="0.1" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></div>
  <div className="setting"><div><Volume2/><span><strong>AUDIO OFFSET</strong><small>Shift note timing to match your device</small></span></div><output>{offset} ms</output><input type="range" min="-200" max="200" step="5" value={offset} onChange={e=>setOffset(Number(e.target.value))}/></div>
  <div className="graphics-setting">
   <div className="theme-heading"><div><strong>GRAPHICS QUALITY</strong><small>Lower effects for smoother gameplay</small></div><span>{graphicsMode==='LOW'?'Performance':'Full effects'}</span></div>
   <div className="graphics-options"><button aria-pressed={graphicsMode==='FULL'} className={graphicsMode==='FULL'?'active':''} onClick={()=>setGraphicsMode('FULL')}><Sparkles/><span><strong>FULL</strong><small>All visual effects</small></span></button><button aria-pressed={graphicsMode==='LOW'} className={graphicsMode==='LOW'?'active':''} onClick={()=>setGraphicsMode('LOW')}><Gauge/><span><strong>LOW</strong><small>Maximum performance</small></span></button></div>
  </div>
  <div className="theme-setting">
   <div className="theme-heading"><div><strong>NOTE STYLE</strong><small>Unlock new circular designs as you level up</small></div><span>{noteThemes.find(theme=>theme.id===noteTheme)?.label}</span></div>
   <div className="theme-options">{noteThemes.map(theme=>{const locked=profile.level<theme.unlockLevel;return <button key={theme.id} disabled={locked} aria-pressed={noteTheme===theme.id} className={(noteTheme===theme.id?'active ':'')+(locked?'locked':'')} onClick={()=>setNoteTheme(theme.id)}><i className={'theme-shape '+theme.id.toLowerCase()}/><strong>{theme.label}</strong><small>{locked?'LEVEL '+theme.unlockLevel:'UNLOCKED'}</small></button>})}</div>
  </div>
  <div className="theme-setting pad-setting">
   <div className="theme-heading"><div><strong>HIT PAD DESIGN</strong><small>Equip a different gameplay pad style</small></div><span>{padThemes.find(theme=>theme.id===padTheme)?.label}</span></div>
   <div className="theme-options pad-options">{padThemes.map(theme=>{const locked=profile.level<theme.unlockLevel;return <button key={theme.id} disabled={locked} aria-pressed={padTheme===theme.id} className={(padTheme===theme.id?'active ':'')+(locked?'locked':'')} onClick={()=>setPadTheme(theme.id)}><i className={'pad-swatch '+theme.id.toLowerCase()}><b/></i><strong>{theme.label}</strong><small>{locked?'LEVEL '+theme.unlockLevel:'UNLOCKED'}</small></button>})}</div>
  </div>
  <div className="how"><h3>HOW TO PLAY</h3><p>Tap the three pads when notes meet the bright judgment line. Desktop players can use D, F and J. Every ten-note streak increases the score multiplier, up to 4×. For long notes, keep holding until the glowing tail reaches the judgment line.</p><button className="tutorial-replay" onClick={replayTutorial}><Play/> REPLAY TUTORIAL</button></div>
 </section>
}

function AchievementsScreen({stats,back}:{stats:Stats,back:()=>void}){return <section className="achievementsPage screen"><header><button className="icon" onClick={back} aria-label="Back"><ArrowLeft/></button><div><small>PROGRESSION</small><h2>ACHIEVEMENTS</h2></div><span className="level">{achievements.filter(a=>a.value(stats)>=a.target).length}/{achievements.length}</span></header><div className="achievement-summary"><Trophy/><div><small>TRACKS COMPLETED</small><strong>{stats.songsCompleted}</strong></div><div><small>PERFECT HITS</small><strong>{stats.perfectHits}</strong></div></div><div className="achievement-list">{achievements.map((achievement,index)=>{const value=achievement.value(stats),complete=value>=achievement.target,percent=Math.min(100,value/achievement.target*100);return <div className={'achievement '+(complete?'complete':'')} key={achievement.id}><span>{complete?<Check/>:<Award/>}</span><div><small>ACHIEVEMENT {String(index+1).padStart(2,'0')}</small><strong>{achievement.label}</strong><p>{achievement.detail}</p><i><b style={{width:percent+'%'}}/></i><em>{Math.min(value,achievement.target)} / {achievement.target}</em></div></div>})}</div></section>}

createRoot(document.getElementById('root')!).render(<App/>);
