import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {estimateClock,functionRequest,getClient,localStartFromHost,makeUuid,registerMatchParticipant,type ClockSample,type JudgementEvent,type JudgementKind,type MultiplayerLaunch,type MultiplayerProgress,type MultiplayerSession,type RealtimeChannel,type SupabaseClient,type VerifiedResult} from './multiplayer-common';
export function useMultiplayerSession(launch:MultiplayerLaunch|null,onRematchStart?:(startAt:number,hostStartAt:number,matchId:string,submissionToken:string)=>void):MultiplayerSession{
 const [connected,setConnected]=useState(false),[reconnecting,setReconnecting]=useState(false),[opponent,setOpponent]=useState<MultiplayerProgress|null>(null),[opponentBackgrounded,setOpponentBackgrounded]=useState(false),[localRematch,setLocalRematch]=useState(false),[opponentRematch,setOpponentRematch]=useState(false),[latencyMs,setLatencyMs]=useState<number|null>(launch?.rttMs??null),[clockOffsetMs,setClockOffsetMs]=useState(launch?.clockOffsetMs??0),[verifiedLocal,setVerifiedLocal]=useState<VerifiedResult|null>(null);
 const channelRef=useRef<RealtimeChannel|null>(null),clientRef=useRef<SupabaseClient|null>(null),lastSent=useRef(0),launchRef=useRef(launch),rematchStarted=useRef(false),rematchCallback=useRef(onRematchStart),connectedRef=useRef(false),retryRef=useRef(0),retryTimer=useRef(0),eventsRef=useRef<JudgementEvent[]>([]),latestProgress=useRef<Omit<MultiplayerProgress,'playerId'|'name'>>({score:0,combo:0,accuracy:0}),clockOffsetRef=useRef(launch?.clockOffsetMs??0);
 launchRef.current=launch;rematchCallback.current=onRematchStart;connectedRef.current=connected;clockOffsetRef.current=clockOffsetMs;
 useEffect(()=>{eventsRef.current=[];setVerifiedLocal(null);setLocalRematch(false);setOpponentRematch(false);rematchStarted.current=false;if(launch){setClockOffsetMs(launch.clockOffsetMs);setLatencyMs(launch.rttMs)}},[launch?.matchId,launch?.hostStartAt]);
 const teardown=useCallback(async()=>{const channel=channelRef.current;channelRef.current=null;if(channel){try{await channel.untrack()}catch{}try{await clientRef.current?.removeChannel(channel)}catch{}}},[]);
 const connectRef=useRef<()=>Promise<void>>(async()=>{});
 const scheduleReconnect=useCallback(()=>{if(!launchRef.current)return;clearTimeout(retryTimer.current);setConnected(false);setReconnecting(true);const delays=[500,1000,2000,5000,10000],delay=delays[Math.min(retryRef.current++,delays.length-1)];retryTimer.current=window.setTimeout(()=>{void connectRef.current()},delay)},[]);
 const connect=useCallback(async()=>{const current=launchRef.current;if(!current)return;await teardown();setReconnecting(true);try{const client=await getClient();clientRef.current=client;const channel=client.channel('rhythtap:'+current.roomCode,{config:{broadcast:{self:false,ack:false},presence:{key:current.playerId}}});channelRef.current=channel;let clockSamples:ClockSample[]=[];const sendClockSamples=async()=>{if(current.isHost)return;clockSamples=[];for(let i=0;i<5;i++){const id=`game-${current.playerId}-${Date.now()}-${i}`,t0=Date.now();void channel.send({type:'broadcast',event:'clock-ping',payload:{id,from:current.playerId,t0}});await new Promise(resolve=>setTimeout(resolve,100))}};
   channel.on('broadcast',{event:'clock-ping'},({payload}:{payload:any})=>{if(!current.isHost||payload?.from===current.playerId)return;const t1=Date.now(),t2=Date.now();void channel.send({type:'broadcast',event:'clock-pong',payload:{id:payload.id,to:payload.from,t0:payload.t0,t1,t2}})});
   channel.on('broadcast',{event:'clock-pong'},({payload}:{payload:any})=>{if(current.isHost||payload?.to!==current.playerId)return;const t3=Date.now(),t0=Number(payload.t0),t1=Number(payload.t1),t2=Number(payload.t2),rtt=Math.max(0,(t3-t0)-(t2-t1)),offset=((t1-t0)+(t2-t3))/2;clockSamples.push({rttMs:rtt,offsetMs:offset});if(clockSamples.length>=3){const est=estimateClock(clockSamples);setLatencyMs(est.rttMs);setClockOffsetMs(est.offsetMs);clockOffsetRef.current=est.offsetMs}});
   channel.on('broadcast',{event:'progress'},({payload}:{payload:MultiplayerProgress})=>{if(payload?.playerId!==current.playerId)setOpponent(old=>({...old,...payload}))});channel.on('broadcast',{event:'final'},({payload}:{payload:MultiplayerProgress})=>{if(payload?.playerId!==current.playerId)setOpponent({...payload,finished:true})});channel.on('broadcast',{event:'player-state'},({payload}:{payload:any})=>{if(payload?.playerId!==current.playerId)setOpponentBackgrounded(Boolean(payload.backgrounded))});channel.on('broadcast',{event:'sync-state-request'},({payload}:{payload:any})=>{if(payload?.from===current.playerId)return;void channel.send({type:'broadcast',event:'sync-state',payload:{...latestProgress.current,playerId:current.playerId,name:current.displayName,backgrounded:document.hidden}})});channel.on('broadcast',{event:'sync-state'},({payload}:{payload:any})=>{if(payload?.playerId!==current.playerId){setOpponent({playerId:payload.playerId,name:payload.name,score:Number(payload.score)||0,combo:Number(payload.combo)||0,accuracy:Number(payload.accuracy)||0});setOpponentBackgrounded(Boolean(payload.backgrounded))}});channel.on('broadcast',{event:'rematch-ready'},({payload}:{payload:any})=>{if(payload?.playerId!==current.playerId)setOpponentRematch(true)});channel.on('broadcast',{event:'rematch-start'},async({payload}:{payload:any})=>{if(!payload?.hostStartAt||!payload?.matchId)return;try{const registration=await registerMatchParticipant({matchId:payload.matchId,roomCode:current.roomCode,playerId:current.playerId,displayName:current.displayName,isHost:false,songId:current.songId,difficulty:current.difficulty}),localStart=localStartFromHost(payload.hostStartAt,clockOffsetRef.current);rematchCallback.current?.(localStart,payload.hostStartAt,payload.matchId,registration.submissionToken)}catch{setConnected(false)}});
   channel.subscribe(async(state:string)=>{if(channelRef.current!==channel)return;if(state==='SUBSCRIBED'){retryRef.current=0;setConnected(true);setReconnecting(false);await channel.track({playerId:current.playerId,name:current.displayName,playing:true,joinedAt:Date.now()});void channel.send({type:'broadcast',event:'sync-state-request',payload:{from:current.playerId}});void sendClockSamples()}else if(state==='CHANNEL_ERROR'||state==='TIMED_OUT'||state==='CLOSED')scheduleReconnect()});
  }catch{scheduleReconnect()}},[teardown,scheduleReconnect]);
 connectRef.current=connect;
 useEffect(()=>{if(!launch)return;void connect();const wake=()=>{if(document.visibilityState==='visible'||navigator.onLine){if(!connectedRef.current)void connectRef.current()}};const visibility=()=>{if(document.visibilityState==='visible'&&!connectedRef.current)void connectRef.current()};addEventListener('online',wake);addEventListener('pageshow',wake);document.addEventListener('visibilitychange',visibility);return()=>{clearTimeout(retryTimer.current);removeEventListener('online',wake);removeEventListener('pageshow',wake);document.removeEventListener('visibilitychange',visibility);void teardown()}},[launch?.roomCode,launch?.playerId,connect,teardown]);
 const send=useCallback((event:'progress'|'final',progress:Omit<MultiplayerProgress,'playerId'|'name'|'finished'>)=>{const current=launchRef.current,channel=channelRef.current;if(!current||!channel)return;latestProgress.current=progress;void channel.send({type:'broadcast',event,payload:{...progress,playerId:current.playerId,name:current.displayName,finished:event==='final'}})},[]);
 const publishProgress=useCallback((progress:Omit<MultiplayerProgress,'playerId'|'name'>)=>{latestProgress.current=progress;const now=performance.now();if(!progress.finished&&now-lastSent.current<120)return;lastSent.current=now;send('progress',progress)},[send]);
 const recordJudgement=useCallback((kind:JudgementKind,noteId:number,lane:number,atMs:number)=>{if(!launchRef.current||!Number.isInteger(noteId)||!Number.isInteger(lane))return;const events=eventsRef.current;if(events.length>=10000)return;events.push({kind,noteId,lane,atMs:Math.max(0,Math.round(atMs))})},[]);
 const publishFinal=useCallback((progress:Omit<MultiplayerProgress,'playerId'|'name'|'finished'>)=>{const current=launchRef.current;if(!current)return;const pending={...progress,validation:'pending' as const};send('progress',pending);void (async()=>{try{const response=await functionRequest({action:'finalize',matchId:current.matchId,submissionToken:current.submissionToken,roomCode:current.roomCode,playerId:current.playerId,displayName:current.displayName,songId:current.songId,difficulty:current.difficulty,events:eventsRef.current});const verified:VerifiedResult={score:Number(response.score)||0,accuracy:Number(response.accuracy)||0,maxCombo:Number(response.maxCombo)||0,eventCount:Number(response.eventCount)||0,validation:'verified'};setVerifiedLocal(verified);send('final',{score:verified.score,combo:verified.maxCombo,accuracy:verified.accuracy,validation:'verified'})}catch{const fallback:VerifiedResult={score:progress.score,accuracy:progress.accuracy,maxCombo:progress.combo,eventCount:eventsRef.current.length,validation:'unverified'};setVerifiedLocal(fallback);send('final',{...progress,validation:'unverified'})}})()},[send]);
 const requestRematch=useCallback(()=>{const current=launchRef.current,channel=channelRef.current;if(!current||!channel)return;setLocalRematch(true);void channel.send({type:'broadcast',event:'rematch-ready',payload:{playerId:current.playerId}})},[]);
 useEffect(()=>{const current=launchRef.current,channel=channelRef.current;if(!current?.isHost||!channel||!localRematch||!opponentRematch||rematchStarted.current)return;rematchStarted.current=true;void(async()=>{try{const matchId=makeUuid(),registration=await registerMatchParticipant({matchId,roomCode:current.roomCode,playerId:current.playerId,displayName:current.displayName,isHost:true,songId:current.songId,difficulty:current.difficulty}),hostStartAt=registration.hostStartAt;void channel.send({type:'broadcast',event:'rematch-start',payload:{hostStartAt,matchId}});rematchCallback.current?.(hostStartAt,hostStartAt,matchId,registration.submissionToken)}catch{rematchStarted.current=false}})()},[localRematch,opponentRematch]);
 const reconnect=useCallback(async()=>{if(connectedRef.current)return;await connectRef.current()},[]);
 const targetElapsedMs=useCallback(()=>{const current=launchRef.current;if(!current)return 0;const hostNow=Date.now()+(current.isHost?0:clockOffsetMs);return Math.max(0,hostNow-current.hostStartAt)},[clockOffsetMs]);
 const setBackgrounded=useCallback((hidden:boolean)=>{const current=launchRef.current,channel=channelRef.current;if(!current||!channel)return;void channel.send({type:'broadcast',event:'player-state',payload:{playerId:current.playerId,backgrounded:hidden}});if(!hidden&&!connectedRef.current)void connectRef.current()},[]);
 return useMemo(()=>({enabled:Boolean(launch),launch,connected,reconnecting,opponent,opponentBackgrounded,localRematch,opponentRematch,latencyMs,clockOffsetMs,verifiedLocal,publishProgress,publishFinal,recordJudgement,requestRematch,reconnect,targetElapsedMs,setBackgrounded}),[launch,connected,reconnecting,opponent,opponentBackgrounded,localRematch,opponentRematch,latencyMs,clockOffsetMs,verifiedLocal,publishProgress,publishFinal,recordJudgement,requestRematch,reconnect,targetElapsedMs,setBackgrounded]);
}
