import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Check,Copy,LogIn,LogOut,Search,ShieldCheck,Trophy,User,UserPlus,Users,Zap} from 'lucide-react';
import {SUPABASE_ANON_KEY,SUPABASE_ESM,SUPABASE_URL} from './multiplayer-common';
import './player-account.css';

export type CloudPlayerProfile={
 userId:string;username:string;displayName:string;bio:string;accent:'cyan'|'violet'|'pink'|'lime'|'gold';isPublic:boolean;
 xp:number;level:number;songsCompleted:number;perfectHits:number;bestCombo:number;createdAt:string;
};
export type CloudSongScore={songId:string;difficulty:'EASY'|'NORMAL'|'HARD';highScore:number;bestAccuracy:number;bestCombo:number;plays:number};
export type ProgressAward={xp:number;level:number;songsCompleted:number;perfectHits:number;bestCombo:number;xpAwarded:number;dailyBonus:number};
export type PlayerAccountController={
 loading:boolean;userId:string|null;email:string|null;profile:CloudPlayerProfile|null;notice:string;error:string;
 signUp:(email:string,password:string,username:string)=>Promise<void>;signIn:(email:string,password:string)=>Promise<void>;signOut:()=>Promise<void>;
 updateProfile:(input:{username:string;displayName:string;bio:string;accent:CloudPlayerProfile['accent'];isPublic:boolean})=>Promise<void>;
 refresh:()=>Promise<void>;recordGame:(input:{songId:string;difficulty:string;score:number;accuracy:number;maxCombo:number;perfectHits:number})=>Promise<ProgressAward|null>;
 searchProfiles:(query:string)=>Promise<CloudPlayerProfile[]>;loadPublicProfile:(username:string)=>Promise<{profile:CloudPlayerProfile;scores:CloudSongScore[]}|null>;
};

type SupabaseClient=any;
let accountClientPromise:Promise<SupabaseClient>|null=null;
const getAccountClient=()=>{if(accountClientPromise)return accountClientPromise;accountClientPromise=(async()=>{const importer=new Function('url','return import(url)') as (url:string)=>Promise<any>;const module=await importer(SUPABASE_ESM);return module.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'rhythtap-account-auth'}})})();return accountClientPromise};
const normalizeProfile=(row:any):CloudPlayerProfile=>({userId:String(row.user_id),username:String(row.username),displayName:String(row.display_name||row.username),bio:String(row.bio||''),accent:(['cyan','violet','pink','lime','gold'].includes(row.accent)?row.accent:'cyan') as CloudPlayerProfile['accent'],isPublic:Boolean(row.is_public),xp:Number(row.xp)||0,level:Number(row.level)||1,songsCompleted:Number(row.songs_completed)||0,perfectHits:Number(row.perfect_hits)||0,bestCombo:Number(row.best_combo)||0,createdAt:String(row.created_at||'')});
const normalizeScore=(row:any):CloudSongScore=>({songId:String(row.song_id),difficulty:String(row.difficulty) as CloudSongScore['difficulty'],highScore:Number(row.high_score)||0,bestAccuracy:Number(row.best_accuracy)||0,bestCombo:Number(row.best_combo)||0,plays:Number(row.plays)||0});
const publicProfileUrl=(username:string)=>`${location.origin}${import.meta.env.BASE_URL}#player/${encodeURIComponent(username)}`;

export function usePlayerAccount():PlayerAccountController{
 const[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[profile,setProfile]=useState<CloudPlayerProfile|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const fetchProfile=useCallback(async(client:SupabaseClient,id:string)=>{const{data,error:queryError}=await client.from('player_profiles').select('*').eq('user_id',id).maybeSingle();if(queryError)throw queryError;setProfile(data?normalizeProfile(data):null)},[]);
 const refresh=useCallback(async()=>{const client=await getAccountClient(),{data}=await client.auth.getSession(),session=data?.session||null;setUserId(session?.user?.id||null);setEmail(session?.user?.email||null);if(session?.user?.id)await fetchProfile(client,session.user.id);else setProfile(null)},[fetchProfile]);
 useEffect(()=>{let mounted=true,subscription:any;(async()=>{try{const client=await getAccountClient();if(!mounted)return;await refresh();const listener=client.auth.onAuthStateChange((_event:string,session:any)=>{if(!mounted)return;setUserId(session?.user?.id||null);setEmail(session?.user?.email||null);if(session?.user?.id)void fetchProfile(client,session.user.id);else setProfile(null)});subscription=listener.data.subscription}catch(e:any){if(mounted)setError(String(e?.message||e))}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false;subscription?.unsubscribe?.()}},[fetchProfile,refresh]);
 const signUp=useCallback(async(address:string,password:string,username:string)=>{setError('');setNotice('');const clean=username.trim();if(!/^[A-Za-z0-9_]{3,20}$/.test(clean)){setError('Username must be 3–20 letters, numbers, or underscores.');return}const client=await getAccountClient(),{data,error:authError}=await client.auth.signUp({email:address.trim(),password,options:{data:{username:clean,display_name:clean},emailRedirectTo:`${location.origin}${import.meta.env.BASE_URL}`}});if(authError){setError(authError.message);return}if(data?.session){setNotice('Account created and signed in.');await refresh()}else setNotice('Account created. Check your email to verify it, then sign in.')},[refresh]);
 const signIn=useCallback(async(address:string,password:string)=>{setError('');setNotice('');const client=await getAccountClient(),{error:authError}=await client.auth.signInWithPassword({email:address.trim(),password});if(authError){setError(authError.message);return}setNotice('Signed in.');await refresh()},[refresh]);
 const signOut=useCallback(async()=>{setError('');setNotice('');const client=await getAccountClient();await client.auth.signOut();setProfile(null);setUserId(null);setEmail(null);setNotice('Signed out.')},[]);
 const updateProfile=useCallback(async(input:{username:string;displayName:string;bio:string;accent:CloudPlayerProfile['accent'];isPublic:boolean})=>{if(!userId)return;setError('');const username=input.username.trim(),displayName=input.displayName.trim();if(!/^[A-Za-z0-9_]{3,20}$/.test(username)){setError('Username must be 3–20 letters, numbers, or underscores.');return}if(!displayName||displayName.length>32||input.bio.length>160){setError('Check your display name and bio length.');return}const client=await getAccountClient(),{data,error:updateError}=await client.from('player_profiles').update({username,display_name:displayName,bio:input.bio,accent:input.accent,is_public:input.isPublic}).eq('user_id',userId).select('*').single();if(updateError){setError(updateError.code==='23505'?'That username is already taken.':updateError.message);return}setProfile(normalizeProfile(data));setNotice('Profile updated.')},[userId]);
 const recordGame=useCallback(async(input:{songId:string;difficulty:string;score:number;accuracy:number;maxCombo:number;perfectHits:number})=>{if(!userId)return null;try{const client=await getAccountClient(),{data,error:rpcError}=await client.rpc('record_player_game',{p_song_id:input.songId,p_difficulty:input.difficulty,p_score:Math.max(0,Math.round(input.score)),p_accuracy:Math.max(0,Math.min(100,input.accuracy)),p_max_combo:Math.max(0,Math.round(input.maxCombo)),p_perfect_hits:Math.max(0,Math.round(input.perfectHits))});if(rpcError)throw rpcError;const row=Array.isArray(data)?data[0]:data;if(!row)return null;const award:ProgressAward={xp:Number(row.xp),level:Number(row.level),songsCompleted:Number(row.songs_completed),perfectHits:Number(row.perfect_hits),bestCombo:Number(row.best_combo),xpAwarded:Number(row.xp_awarded),dailyBonus:Number(row.daily_bonus)};setProfile(current=>current?{...current,xp:award.xp,level:award.level,songsCompleted:award.songsCompleted,perfectHits:award.perfectHits,bestCombo:award.bestCombo}:current);return award}catch(e:any){console.warn('[account] progress sync failed',e?.message||e);return null}},[userId]);
 const searchProfiles=useCallback(async(query:string)=>{const client=await getAccountClient();let request=client.from('player_profiles').select('*').eq('is_public',true).order('level',{ascending:false}).order('xp',{ascending:false}).limit(24);const clean=query.trim();if(clean)request=request.or(`username.ilike.%${clean.replace(/[%_,()]/g,'')}%,display_name.ilike.%${clean.replace(/[%_,()]/g,'')}%`);const{data,error:queryError}=await request;if(queryError)throw queryError;return(data||[]).map(normalizeProfile)},[]);
 const loadPublicProfile=useCallback(async(username:string)=>{const client=await getAccountClient(),{data,error:profileError}=await client.from('player_profiles').select('*').ilike('username',username).maybeSingle();if(profileError||!data||(!data.is_public&&data.user_id!==userId))return null;const{data:scores}=await client.from('player_song_scores').select('*').eq('user_id',data.user_id).order('high_score',{ascending:false}).limit(12);return{profile:normalizeProfile(data),scores:(scores||[]).map(normalizeScore)}},[userId]);
 return{loading,userId,email,profile,notice,error,signUp,signIn,signOut,updateProfile,refresh,recordGame,searchProfiles,loadPublicProfile};
}

const Stat=({label,value}:{label:string,value:React.ReactNode})=><div className="account-stat"><small>{label}</small><strong>{value}</strong></div>;
const PlayerCard=({player,onOpen}:{player:CloudPlayerProfile,onOpen:(username:string)=>void})=><button className={`player-result accent-${player.accent}`} onClick={()=>onOpen(player.username)}><div className="profile-avatar"><User/></div><div><strong>{player.displayName}</strong><small>@{player.username} · LV {player.level}</small></div><span>{player.songsCompleted} SETS</span></button>;

export function AccountScreen({account,back}:{account:PlayerAccountController,back:()=>void}){
 const[mode,setMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),[editing,setEditing]=useState(false),[search,setSearch]=useState(''),[players,setPlayers]=useState<CloudPlayerProfile[]>([]),[selected,setSelected]=useState<string|null>(null),[publicData,setPublicData]=useState<{profile:CloudPlayerProfile;scores:CloudSongScore[]}|null>(null);
 const[edit,setEdit]=useState({username:'',displayName:'',bio:'',accent:'cyan' as CloudPlayerProfile['accent'],isPublic:true});
 useEffect(()=>{if(account.profile)setEdit({username:account.profile.username,displayName:account.profile.displayName,bio:account.profile.bio,accent:account.profile.accent,isPublic:account.profile.isPublic})},[account.profile]);
 const runSearch=useCallback(async()=>{try{setPlayers(await account.searchProfiles(search))}catch{}},[account,search]);
 useEffect(()=>{if(account.profile)void runSearch()},[account.profile?.userId]);
 const open=async(name:string)=>{setSelected(name);setPublicData(await account.loadPublicProfile(name))};
 if(selected&&publicData)return <PublicProfileCard data={publicData} back={()=>{setSelected(null);setPublicData(null)}}/>;
 return <section className="account-screen screen"><div className="screen-top"><button className="icon" onClick={back}><ArrowLeft/></button><div><small>RHYTHMTAP ID</small><h2>{account.profile?'PLAYER PROFILE':'ACCOUNT'}</h2></div>{account.profile&&<button className="secondary compact" onClick={()=>void account.signOut()}><LogOut/> SIGN OUT</button>}</div>
  {!account.profile?<div className="auth-wrap"><div className="auth-card"><div className="auth-icon">{mode==='signin'?<LogIn/>:<UserPlus/>}</div><h1>{mode==='signin'?'WELCOME BACK':'CREATE YOUR RHYTHMTAP ID'}</h1><p>Your levels, stats and public profile follow you across devices.</p>{mode==='signup'&&<label>USERNAME<input value={username} onChange={e=>setUsername(e.target.value)} autoCapitalize="none" placeholder="beatmaster" maxLength={20}/></label>}<label>EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com"/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signin'?'current-password':'new-password'} minLength={6}/></label>{account.error&&<div className="account-error">{account.error}</div>}{account.notice&&<div className="account-notice">{account.notice}</div>}<button className="primary" onClick={()=>void(mode==='signin'?account.signIn(email,password):account.signUp(email,password,username))}>{mode==='signin'?<><LogIn/> SIGN IN</>:<><UserPlus/> CREATE ACCOUNT</>}</button><button className="auth-switch" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Need an account? Create one':'Already have an account? Sign in'}</button></div></div>:
  <div className="account-content"><div className={`profile-hero accent-${account.profile.accent}`}><div className="profile-avatar large"><User/></div><div className="profile-identity"><small>LEVEL {account.profile.level}</small><h1>{account.profile.displayName}</h1><span>@{account.profile.username}</span><p>{account.profile.bio||'No bio yet.'}</p></div><button className="secondary compact" onClick={()=>setEditing(!editing)}>{editing?'CANCEL':'EDIT PROFILE'}</button></div>
  <div className="account-stats"><Stat label="XP" value={account.profile.xp.toLocaleString()}/><Stat label="TRACKS" value={account.profile.songsCompleted}/><Stat label="PERFECT HITS" value={account.profile.perfectHits.toLocaleString()}/><Stat label="BEST COMBO" value={account.profile.bestCombo}/></div>
  {editing&&<div className="profile-editor"><label>USERNAME<input value={edit.username} onChange={e=>setEdit(v=>({...v,username:e.target.value}))} maxLength={20}/></label><label>DISPLAY NAME<input value={edit.displayName} onChange={e=>setEdit(v=>({...v,displayName:e.target.value}))} maxLength={32}/></label><label>BIO<textarea value={edit.bio} onChange={e=>setEdit(v=>({...v,bio:e.target.value}))} maxLength={160}/><span>{edit.bio.length}/160</span></label><label>ACCENT<select value={edit.accent} onChange={e=>setEdit(v=>({...v,accent:e.target.value as CloudPlayerProfile['accent']}))}><option value="cyan">Cyan</option><option value="violet">Violet</option><option value="pink">Pink</option><option value="lime">Lime</option><option value="gold">Gold</option></select></label><label className="privacy-row"><input type="checkbox" checked={edit.isPublic} onChange={e=>setEdit(v=>({...v,isPublic:e.target.checked}))}/><span><strong>PUBLIC PROFILE</strong><small>Allow other players to find and view your progression.</small></span></label>{account.error&&<div className="account-error">{account.error}</div>}<button className="primary" onClick={()=>void account.updateProfile(edit)}><Check/> SAVE PROFILE</button></div>}
  <div className="share-card"><ShieldCheck/><div><small>YOUR PUBLIC PLAYER CARD</small><strong>{account.profile.isPublic?'Visible to other players':'Private'}</strong></div>{account.profile.isPublic&&<button className="secondary compact" onClick={()=>void navigator.clipboard?.writeText(publicProfileUrl(account.profile!.username))}><Copy/> COPY LINK</button>}</div>
  <div className="players-panel"><div className="panel-title"><div><small>COMMUNITY</small><h2>FIND PLAYERS</h2></div><Users/></div><div className="player-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void runSearch()} placeholder="Search username or display name"/><button onClick={()=>void runSearch()}>SEARCH</button></div><div className="player-results">{players.map(player=><PlayerCard key={player.userId} player={player} onOpen={open}/>)}</div></div></div>}
 </section>;
}

function PublicProfileCard({data,back}:{data:{profile:CloudPlayerProfile;scores:CloudSongScore[]},back:()=>void}){const p=data.profile;return <section className="account-screen screen"><div className="screen-top"><button className="icon" onClick={back}><ArrowLeft/></button><div><small>PUBLIC PROFILE</small><h2>@{p.username}</h2></div><button className="secondary compact" onClick={()=>void navigator.clipboard?.writeText(publicProfileUrl(p.username))}><Copy/> SHARE</button></div><div className="account-content"><div className={`profile-hero accent-${p.accent}`}><div className="profile-avatar large"><User/></div><div className="profile-identity"><small>LEVEL {p.level}</small><h1>{p.displayName}</h1><span>@{p.username}</span><p>{p.bio||'RhythmTap player'}</p></div><div className="profile-badge"><Zap/> LV {p.level}</div></div><div className="account-stats"><Stat label="XP" value={p.xp.toLocaleString()}/><Stat label="TRACKS" value={p.songsCompleted}/><Stat label="PERFECT HITS" value={p.perfectHits.toLocaleString()}/><Stat label="BEST COMBO" value={p.bestCombo}/></div><div className="score-showcase"><div className="panel-title"><div><small>SHOWCASE</small><h2>TOP SCORES</h2></div><Trophy/></div>{data.scores.length?data.scores.map(score=><div className="score-row" key={`${score.songId}-${score.difficulty}`}><div><strong>{score.songId.replaceAll('-',' ').toUpperCase()}</strong><small>{score.difficulty} · {score.bestAccuracy.toFixed(1)}% · {score.bestCombo} combo</small></div><span>{score.highScore.toLocaleString()}</span></div>):<div className="empty-profile">No public scores yet.</div>}</div></div></section>}

export function PublicProfileScreen({account,back}:{account:PlayerAccountController,back:()=>void}){const username=useMemo(()=>{const hash=location.hash.replace(/^#player\//,'');try{return decodeURIComponent(hash)}catch{return hash}},[]),[data,setData]=useState<{profile:CloudPlayerProfile;scores:CloudSongScore[]}|null|null>(null);useEffect(()=>{void account.loadPublicProfile(username).then(setData)},[account.loadPublicProfile,username]);if(data===null)return <section className="account-screen screen"><div className="screen-top"><button className="icon" onClick={back}><ArrowLeft/></button><div><small>PUBLIC PROFILE</small><h2>LOADING…</h2></div></div></section>;if(!data)return <section className="account-screen screen"><div className="screen-top"><button className="icon" onClick={back}><ArrowLeft/></button><div><small>PUBLIC PROFILE</small><h2>NOT FOUND</h2></div></div><div className="empty-profile">This player profile is private or unavailable.</div></section>;return <PublicProfileCard data={data} back={back}/>}
