import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Check,Crown,Gamepad2,Lock,Medal,Play,Search,Star,Swords,Trophy,UserPlus,Users,X} from 'lucide-react';
import {SUPABASE_ANON_KEY,SUPABASE_ESM,SUPABASE_URL,flattenPresence,makeCode} from './multiplayer-common';
import './tour-social-ranked.css';

export type TourDifficulty='EASY'|'NORMAL'|'HARD';
export type TourSong={id:string,title:string,artist:string,unlockLevel:number};
export type TourRun={gigId:string};
type TourProgress={gigId:string,stars:number,bestScore:number,bestAccuracy:number,bestDifficulty:TourDifficulty};
type SocialProfile={userId:string,username:string,displayName:string,level:number,accent:string};
type FriendRow={id:string,requester_id:string,addressee_id:string,status:string,created_at:string};
type InviteRow={id:string,sender_id:string,recipient_id:string,room_code:string,status:string,created_at:string,expires_at:string};
type RankedRow={user_id:string,rating:number,wins:number,losses:number,draws:number,matches_played:number,best_rating:number};

type SupabaseClient=any;
let appClientPromise:Promise<SupabaseClient>|null=null;
const getAppClient=()=>{if(appClientPromise)return appClientPromise;appClientPromise=(async()=>{const importer=new Function('url','return import(url)') as (url:string)=>Promise<any>;const module=await importer(SUPABASE_ESM);return module.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'rhythtap-account-auth'},realtime:{params:{eventsPerSecond:10}}})})();return appClientPromise};

const TOUR_KEY='rhythtap-tour-progress-v1';
const tours=[
 {id:'basement',venue:'BASEMENT SHOW',city:'OPENING NIGHT',songId:'sickness',min:'EASY' as TourDifficulty,need:0},
 {id:'skatepark',venue:'SKATEPARK SET',city:'FIRST FOLLOWING',songId:'never-left',min:'EASY' as TourDifficulty,need:2},
 {id:'club',venue:'CLUB STAGE',city:'PACKED HOUSE',songId:'kryptonite',min:'EASY' as TourDifficulty,need:4},
 {id:'theatre',venue:'THEATRE NIGHT',city:'THE SLOW SET',songId:'my-immortal',min:'NORMAL' as TourDifficulty,need:6},
 {id:'arena',venue:'ARENA SUPPORT',city:'BIG STAGE',songId:'crazy-train',min:'NORMAL' as TourDifficulty,need:8},
 {id:'midnight',venue:'MIDNIGHT FEST',city:'LOUDER CROWD',songId:'fly-eagle',min:'NORMAL' as TourDifficulty,need:10},
 {id:'underground',venue:'UNDERGROUND HEADLINE',city:'NO WARMUP',songId:'kill-you',min:'HARD' as TourDifficulty,need:12},
 {id:'headliner',venue:'FINAL HEADLINER',city:'TOUR FINALE',songId:'through-fire-flames',min:'HARD' as TourDifficulty,need:15},
];
const diffRank=(d:TourDifficulty)=>d==='EASY'?0:d==='NORMAL'?1:2;
const starsFor=(accuracy:number)=>accuracy>=95?3:accuracy>=85?2:accuracy>=70?1:0;
const readLocalTour=():TourProgress[]=>{try{const rows=JSON.parse(localStorage.getItem(TOUR_KEY)||'[]');return Array.isArray(rows)?rows:[]}catch{return[]}};
const saveLocalTour=(rows:TourProgress[])=>localStorage.setItem(TOUR_KEY,JSON.stringify(rows));

export async function recordTourResult(userId:string|null,run:TourRun|null,score:number,accuracy:number,difficulty:TourDifficulty){
 if(!run)return;
 const stars=starsFor(accuracy),local=readLocalTour(),existing=local.find(x=>x.gigId===run.gigId),next:TourProgress={gigId:run.gigId,stars:Math.max(stars,existing?.stars||0),bestScore:Math.max(score,existing?.bestScore||0),bestAccuracy:Math.max(accuracy,existing?.bestAccuracy||0),bestDifficulty:diffRank(difficulty)>=diffRank(existing?.bestDifficulty||'EASY')?difficulty:(existing?.bestDifficulty||'EASY')};
 saveLocalTour([...local.filter(x=>x.gigId!==run.gigId),next]);
 if(!userId)return;
 try{const client=await getAppClient();const{data}=await client.from('player_tour_progress').select('*').eq('user_id',userId).eq('gig_id',run.gigId).maybeSingle();const cloud=data||{};await client.from('player_tour_progress').upsert({user_id:userId,gig_id:run.gigId,stars:Math.max(stars,Number(cloud.stars)||0),best_score:Math.max(score,Number(cloud.best_score)||0),best_accuracy:Math.max(accuracy,Number(cloud.best_accuracy)||0),best_difficulty:diffRank(difficulty)>=diffRank((cloud.best_difficulty||'EASY') as TourDifficulty)?difficulty:cloud.best_difficulty||'EASY',completed_at:stars>0?(cloud.completed_at||new Date().toISOString()):cloud.completed_at,updated_at:new Date().toISOString()})}catch(e){console.warn('[tour] cloud progress sync failed',e)}
}

export function TourScreen({songs,profileLevel,userId,back,onPlay}:{songs:TourSong[],profileLevel:number,userId:string|null,back:()=>void,onPlay:(songId:string,difficulty:TourDifficulty,run:TourRun)=>void}){
 const[progress,setProgress]=useState<TourProgress[]>(readLocalTour()),[loading,setLoading]=useState(Boolean(userId));
 useEffect(()=>{let mounted=true;(async()=>{if(!userId){setLoading(false);return}try{const client=await getAppClient(),{data}=await client.from('player_tour_progress').select('*').eq('user_id',userId);if(!mounted)return;const cloud=(data||[]).map((r:any)=>({gigId:String(r.gig_id),stars:Number(r.stars)||0,bestScore:Number(r.best_score)||0,bestAccuracy:Number(r.best_accuracy)||0,bestDifficulty:String(r.best_difficulty||'EASY') as TourDifficulty}));if(cloud.length){setProgress(cloud);saveLocalTour(cloud)}}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[userId]);
 const total=progress.reduce((n,p)=>n+p.stars,0),songMap=useMemo(()=>new Map(songs.map(s=>[s.id,s])),[songs]);
 return <section className="tsr-screen screen"><Header eyebrow="CAREER" title="RHYTHMTAP TOUR" back={back}/><div className="tsr-wrap"><div className="tour-hero"><div><small>TOUR STARS</small><strong>{total} / {tours.length*3}</strong><p>Earn stars with accuracy. Better performances replace your previous result.</p></div><Trophy/></div><div className="tour-line">{tours.map((gig,index)=>{const song=songMap.get(gig.songId),p=progress.find(x=>x.gigId===gig.id),unlocked=total>=gig.need&&profileLevel>=(song?.unlockLevel||1),complete=(p?.stars||0)>0;return <article key={gig.id} className={'tour-stop '+(unlocked?'':'locked')}><div className="tour-index">{complete?<Check/>:unlocked?index+1:<Lock/>}</div><div className="tour-copy"><small>{gig.city}</small><h3>{gig.venue}</h3><strong>{song?.title||gig.songId}</strong><span>{song?.artist||''}</span><div className="tour-stars">{[1,2,3].map(n=><Star key={n} fill={(p?.stars||0)>=n?'currentColor':'none'}/>)}</div></div><div className="tour-action"><small>{unlocked?`MIN ${gig.min}`:`NEED ${gig.need} STARS`}</small><button className="primary compact" disabled={!unlocked||!song||loading} onClick={()=>song&&onPlay(song.id,gig.min,{gigId:gig.id})}><Play/> PLAY</button></div></article>})}</div></div></section>;
}

const normalizeProfile=(r:any):SocialProfile=>({userId:String(r.user_id),username:String(r.username),displayName:String(r.display_name||r.username),level:Number(r.level)||1,accent:String(r.accent||'cyan')});
async function loadProfiles(client:SupabaseClient,ids:string[]){if(!ids.length)return[] as SocialProfile[];const{data}=await client.from('player_profiles').select('user_id,username,display_name,level,accent').in('user_id',[...new Set(ids)]);return(data||[]).map(normalizeProfile)}

export function SocialScreen({userId,back,onBattle}:{userId:string|null,back:()=>void,onBattle:(roomCode:string,isHost:boolean)=>void}){
 const[query,setQuery]=useState(''),[results,setResults]=useState<SocialProfile[]>([]),[requests,setRequests]=useState<FriendRow[]>([]),[profiles,setProfiles]=useState<SocialProfile[]>([]),[invites,setInvites]=useState<InviteRow[]>([]),[online,setOnline]=useState<Set<string>>(new Set()),[message,setMessage]=useState('');
 const refresh=useCallback(async()=>{if(!userId)return;const client=await getAppClient();const[{data:friendData},{data:inviteData}]=await Promise.all([client.from('player_friend_requests').select('*').order('created_at',{ascending:false}),client.from('battle_invites').select('*').eq('status','pending').order('created_at',{ascending:false})]);const f=(friendData||[]) as FriendRow[],i=(inviteData||[]).filter((x:any)=>new Date(x.expires_at).getTime()>Date.now()) as InviteRow[];setRequests(f);setInvites(i);setProfiles(await loadProfiles(client,[...f.flatMap(x=>[x.requester_id,x.addressee_id]),...i.flatMap(x=>[x.sender_id,x.recipient_id])].filter(x=>x!==userId)))},[userId]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(!userId)return;let channel:any,alive=true;(async()=>{const client=await getAppClient(),{data}=await client.auth.getSession(),token=data?.session?.access_token;if(token)await client.realtime.setAuth(token);channel=client.channel('rhythtap:social-presence-v1',{config:{private:true,presence:{key:userId}}});channel.on('presence',{event:'sync'},()=>{if(!alive)return;const ids=flattenPresence(channel.presenceState()).map((x:any)=>String(x.userId||'')).filter(Boolean);setOnline(new Set(ids))});channel.subscribe(async(status:string)=>{if(status==='SUBSCRIBED')await channel.track({userId,onlineAt:new Date().toISOString()})})})();const timer=window.setInterval(()=>void refresh(),5000);return()=>{alive=false;clearInterval(timer);if(channel)void getAppClient().then(c=>c.removeChannel(channel))}},[userId,refresh]);
 const search=async()=>{if(!userId)return;const client=await getAppClient();let request=client.from('player_profiles').select('user_id,username,display_name,level,accent').eq('is_public',true).neq('user_id',userId).limit(20);const clean=query.trim().replace(/[%_,()]/g,'');if(clean)request=request.or(`username.ilike.%${clean}%,display_name.ilike.%${clean}%`);const{data}=await request;setResults((data||[]).map(normalizeProfile))};
 const sendFriend=async(target:string)=>{if(!userId)return;const client=await getAppClient();const existing=requests.find(r=>[r.requester_id,r.addressee_id].includes(userId)&&[r.requester_id,r.addressee_id].includes(target));if(existing&&existing.status==='accepted'){setMessage('Already friends.');return}if(existing)await client.from('player_friend_requests').delete().eq('id',existing.id);const{error}=await client.from('player_friend_requests').insert({requester_id:userId,addressee_id:target,status:'pending'});setMessage(error?.message||'Friend request sent.');await refresh()};
 const respond=async(row:FriendRow,status:'accepted'|'declined')=>{const client=await getAppClient(),{error}=await client.from('player_friend_requests').update({status,updated_at:new Date().toISOString()}).eq('id',row.id);setMessage(error?.message||status.toUpperCase());await refresh()};
 const invite=async(target:string)=>{if(!userId)return;const client=await getAppClient(),code=makeCode(),{error}=await client.from('battle_invites').insert({sender_id:userId,recipient_id:target,room_code:code,status:'pending'});if(error){setMessage(error.message);return}onBattle(code,true)};
 const respondInvite=async(row:InviteRow,status:'accepted'|'declined')=>{const client=await getAppClient(),{error}=await client.from('battle_invites').update({status,updated_at:new Date().toISOString()}).eq('id',row.id);if(error){setMessage(error.message);return}await refresh();if(status==='accepted')onBattle(row.room_code,false)};
 if(!userId)return <section className="tsr-screen screen"><Header eyebrow="SOCIAL" title="FRIENDS + INVITES" back={back}/><div className="tsr-empty"><Users/><h2>RHYTHMTAP ID REQUIRED</h2><p>Sign in from My Profile to add friends, show online status, and send direct battle invites.</p></div></section>;
 const pmap=new Map(profiles.map(p=>[p.userId,p])),friends=requests.filter(r=>r.status==='accepted'),incoming=requests.filter(r=>r.status==='pending'&&r.addressee_id===userId),incomingInvites=invites.filter(i=>i.recipient_id===userId);
 return <section className="tsr-screen screen"><Header eyebrow="SOCIAL" title="FRIENDS + INVITES" back={back}/><div className="tsr-wrap">{message&&<div className="tsr-notice">{message}</div>}{incomingInvites.length>0&&<Panel title="BATTLE INVITES" icon={<Swords/>}>{incomingInvites.map(row=>{const p=pmap.get(row.sender_id);return <div className="social-row" key={row.id}><Avatar online={online.has(row.sender_id)}/><div><strong>{p?.displayName||'PLAYER'}</strong><small>{p?`@${p.username}`:'Battle invite'} · ROOM {row.room_code}</small></div><button onClick={()=>void respondInvite(row,'accepted')}><Check/> ACCEPT</button><button className="danger" onClick={()=>void respondInvite(row,'declined')}><X/></button></div>})}</Panel>}{incoming.length>0&&<Panel title="FRIEND REQUESTS" icon={<UserPlus/>}>{incoming.map(row=>{const p=pmap.get(row.requester_id);return <div className="social-row" key={row.id}><Avatar online={online.has(row.requester_id)}/><div><strong>{p?.displayName||'PLAYER'}</strong><small>{p?`@${p.username}`:'Incoming request'}</small></div><button onClick={()=>void respond(row,'accepted')}><Check/> ADD</button><button className="danger" onClick={()=>void respond(row,'declined')}><X/></button></div>})}</Panel>}<Panel title="FRIENDS" icon={<Users/>}>{friends.length?friends.map(row=>{const id=row.requester_id===userId?row.addressee_id:row.requester_id,p=pmap.get(id),isOnline=online.has(id);return <div className="social-row" key={row.id}><Avatar online={isOnline}/><div><strong>{p?.displayName||'PLAYER'}</strong><small>{p?`@${p.username} · LV ${p.level}`:''} · {isOnline?'ONLINE':'OFFLINE'}</small></div><button disabled={!isOnline} onClick={()=>void invite(id)}><Swords/> BATTLE</button></div>}):<p className="muted">Add players below. Online friends can be invited straight into a private battle.</p>}</Panel><Panel title="FIND PLAYERS" icon={<Search/>}><div className="tsr-search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Username or display name"/><button onClick={()=>void search()}>SEARCH</button></div>{results.map(p=><div className="social-row" key={p.userId}><Avatar online={online.has(p.userId)}/><div><strong>{p.displayName}</strong><small>@{p.username} · LV {p.level}</small></div><button onClick={()=>void sendFriend(p.userId)}><UserPlus/> ADD</button></div>)}</Panel></div></section>;
}

const tierFor=(rating:number)=>rating>=1750?'MASTER':rating>=1500?'DIAMOND':rating>=1300?'PLATINUM':rating>=1100?'GOLD':rating>=900?'SILVER':'BRONZE';
export function RankedScreen({songs,userId,back}:{songs:TourSong[],userId:string|null,back:()=>void}){
 const[ranked,setRanked]=useState<RankedRow[]>([]),[profiles,setProfiles]=useState<SocialProfile[]>([]),[songId,setSongId]=useState(songs[0]?.id||''),[difficulty,setDifficulty]=useState<TourDifficulty>('NORMAL'),[scores,setScores]=useState<any[]>([]),[scoreProfiles,setScoreProfiles]=useState<SocialProfile[]>([]);
 useEffect(()=>{let live=true;(async()=>{const client=await getAppClient(),{data}=await client.from('player_ranked_stats').select('*').order('rating',{ascending:false}).limit(50);if(!live)return;const rows=(data||[]) as RankedRow[];setRanked(rows);setProfiles(await loadProfiles(client,rows.map(r=>r.user_id)))})();return()=>{live=false}},[]);
 useEffect(()=>{let live=true;(async()=>{if(!songId)return;const client=await getAppClient(),{data}=await client.from('player_song_scores').select('*').eq('song_id',songId).eq('difficulty',difficulty).order('high_score',{ascending:false}).limit(50);if(!live)return;const rows=data||[];setScores(rows);setScoreProfiles(await loadProfiles(client,rows.map((r:any)=>String(r.user_id))))})();return()=>{live=false}},[songId,difficulty]);
 const pmap=new Map(profiles.map(p=>[p.userId,p])),smap=new Map(scoreProfiles.map(p=>[p.userId,p])),mine=ranked.find(r=>r.user_id===userId);
 return <section className="tsr-screen screen"><Header eyebrow="COMPETITIVE" title="RANKED + LEADERBOARDS" back={back}/><div className="tsr-wrap">{mine&&<div className="rank-hero"><Medal/><div><small>YOUR RANK</small><h2>{tierFor(mine.rating)}</h2><strong>{mine.rating} RP · {mine.wins}W {mine.losses}L {mine.draws}D</strong></div></div>}<Panel title="RANKED BATTLE" icon={<Crown/>}>{ranked.length?ranked.map((r,index)=>{const p=pmap.get(r.user_id);return <div className={'rank-row '+(r.user_id===userId?'mine':'')} key={r.user_id}><b>#{index+1}</b><div><strong>{p?.displayName||'PLAYER'}</strong><small>{p?`@${p.username}`:''} · {tierFor(r.rating)} · {r.matches_played} MATCHES</small></div><span>{r.rating} RP</span></div>}):<p className="muted">Ranked records begin after verified multiplayer battles complete.</p>}</Panel><Panel title="SONG LEADERBOARD" icon={<Trophy/>}><div className="leader-filters"><select value={songId} onChange={e=>setSongId(e.target.value)}>{songs.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><div>{(['EASY','NORMAL','HARD'] as TourDifficulty[]).map(d=><button className={difficulty===d?'active':''} key={d} onClick={()=>setDifficulty(d)}>{d}</button>)}</div></div>{scores.map((r:any,index)=>{const p=smap.get(String(r.user_id));return <div className={'rank-row '+(String(r.user_id)===userId?'mine':'')} key={`${r.user_id}-${r.song_id}-${r.difficulty}`}><b>#{index+1}</b><div><strong>{p?.displayName||'PLAYER'}</strong><small>{p?`@${p.username}`:''} · {Number(r.best_accuracy||0).toFixed(1)}% · {Number(r.best_combo||0)} COMBO</small></div><span>{Number(r.high_score||0).toLocaleString()}</span></div>})}</Panel></div></section>;
}

function Header({eyebrow,title,back}:{eyebrow:string,title:string,back:()=>void}){return <div className="tsr-top"><button className="icon" onClick={back}><ArrowLeft/></button><div><small>{eyebrow}</small><h2>{title}</h2></div></div>}
function Panel({title,icon,children}:{title:string,icon:React.ReactNode,children:React.ReactNode}){return <div className="tsr-panel"><div className="tsr-panel-title"><div><small>RHYTHMTAP</small><h2>{title}</h2></div>{icon}</div>{children}</div>}
function Avatar({online}:{online:boolean}){return <div className={'social-avatar '+(online?'online':'')}><Gamepad2/><i/></div>}
