create table if not exists public.player_engagement_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  session_id text not null check (char_length(session_id) between 8 and 128),
  event_name text not null check (event_name in ('game_open','home_primary_action','mode_selected','song_selected','difficulty_selected','song_started','song_completed','song_retry','results_continue')),
  song_id text null,
  difficulty text null check (difficulty is null or difficulty in ('EASY','NORMAL','HARD')),
  value double precision null,
  metadata jsonb not null default '{}'::jsonb,
  client_ts timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.player_engagement_events enable row level security;

grant insert on public.player_engagement_events to anon, authenticated;
grant usage, select on sequence public.player_engagement_events_id_seq to anon, authenticated;

create policy "anonymous engagement insert"
on public.player_engagement_events
for insert
to anon
with check (user_id is null);

create policy "authenticated engagement insert"
on public.player_engagement_events
for insert
to authenticated
with check (user_id is null or (select auth.uid()) = user_id);

create index if not exists player_engagement_events_created_at_idx on public.player_engagement_events(created_at desc);
create index if not exists player_engagement_events_event_name_idx on public.player_engagement_events(event_name, created_at desc);
create index if not exists player_engagement_events_user_id_idx on public.player_engagement_events(user_id, created_at desc);
